### ISSUE TITLE
system_tests_tcp_adaptor_tls failing with SSLEOFError

### ISSUE THREAD

**Issue by ganeshmurthy** [skupperproject/skupper-router#1059]
```
DEBUG    root:system_test.py:1917 2023-04-18 18:55:56.378308 TcpAdaptor-testClass: TCP_TEST TLS Start test_authenticate_peer
DEBUG    root:system_test.py:1917 2023-04-18 18:55:56.378864 TcpAdaptor-testClass: Starting ncat ['ncat', 'localhost', '22550', '--ssl-trustfile', '/home/runner/work/skupper-router/skupper-router/skupper-router/tests/ssl_certs/ca-certificate.pem', '--ssl-cert', '/home/runner/work/skupper-router/skupper-router/skupper-router/tests/ssl_certs/client-certificate.pem', '--ssl-key', '/home/runner/work/skupper-router/skupper-router/skupper-router/tests/ssl_certs/client-private-key-no-pass.pem'] and input len=4, name=test_authenticate_peer_INTA_INTA
DEBUG    root:system_test.py:1917 2023-04-18 18:55:56.429074 TcpAdaptor: ECHO_SERVER TcpAdaptor ES_INTA Accepted TLS connection from 127.0.0.1:43538
DEBUG    root:system_test.py:1917 2023-04-18 18:55:56.429408 TcpAdaptor: ECHO_SERVER TcpAdaptor ES_INTA registered TLS selector
DEBUG    root:system_test.py:1917 2023-04-18 18:55:56.438789 TcpAdaptor: ECHO SERVER ssl.SSLWantReadError, recv_data=4
DEBUG    root:system_test.py:1917 2023-04-18 18:55:56.439035 TcpAdaptor: ECHO_SERVER TcpAdaptor ES_INTA read from: 127.0.0.1:43538 len:4: b'abcd', bytes received so far=504518
DEBUG    root:system_test.py:1917 2023-04-18 18:55:56.439261 TcpAdaptor: ECHO_SERVER TcpAdaptor ES_INTA Client closed: flush client input to 127.0.0.1:43538
DEBUG    root:system_test.py:1917 2023-04-18 18:55:56.440039 TcpAdaptor: ECHO_SERVER TcpAdaptor ES_INTA Connection to 127.0.0.1:43538 IOError: Traceback (most recent call last):
  File "/home/runner/work/skupper-router/skupper-router/skupper-router/tests/TCP_echo_server.py", line 307, in do_service
    sent = sock.send(data.outb)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/ssl.py", line 1210, in send
    return self._sslobj.write(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2423)
----------------- generated xml file: /__w/skupper-router/skupper-router/skupper-router/build/tests/junitxmls/system_tests_tcp_adaptor_tls.xml -----------------
=================================================================== short test summary info ====================================================================
FAILED ::TcpTlsAdaptor::test_70_half_closed_INTA_INTA - AssertionError: b'abcd' != b'' : ncat command returned invalid data, expected b'abcd' but got b''
FAILED ::TcpTlsAdaptor::test_71_half_closed_INTA_INTB - AssertionError: b'abcd' != b'' : ncat command returned invalid data, expected b'abcd' but got b''
FAILED ::TcpTlsAdaptor::test_73_half_closed_EA1_EA1 - AssertionError: b'abcd' != b'' : ncat command returned invalid data, expected b'abcd' but got b''
FAILED ::TcpTlsAdaptor::test_74_half_closed_EA1_EB1 - AssertionError: b'abcd' != b'' : ncat command returned invalid data, expected b'abcd' but got b''
FAILED ::TcpTlsAdaptor::test_75_half_closed_EA1_EC2 - AssertionError: b'abcd' != b'' : ncat command returned invalid data, expected b'abcd' but got b''
FAILED ::TcpTlsAdaptor::test_76_half_closed_EA1_EC2_large_message - AssertionError: b'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG[39974 chars]SION' != b'' : ncat command returned invalid data, expected 40019 but got 0
FAILED ::TcpTlsAdaptor::test_77_half_closed_INTA_INTC_large_message - AssertionError: b'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG[39974 chars]SION' != b'' : ncat command returned invalid data, expected 40019 but got 0
FAILED ::TcpTlsAdaptor::test_80_stats - assert 501106 == 501102
FAILED ::TcpTlsAdaptor::test_authenticate_peer - AssertionError: b'abcd' != b'' : ncat command returned invalid data, expected b'abcd' but got b''
===================================================== 9 failed, 27 passed, 1 skipped in 332.56s (0:05:32) ======================================================


97% tests passed, 1 tests failed out of 34
```

https://github.com/skupperproject/skupper-router/actions/runs/4722038931/jobs/8406515198#step:34:4902

**Comment by jiridanek** [comment]
Attempt 1 of a CI job that did not fail with this issue: Resolved version apache-qpid-proton-6424d https://github.com/skupperproject/skupper-router/actions/runs/4722038931/jobs/8376089832#step:5:52

Attempt 2 of the same that did fail with this: Resolved version apache-qpid-proton-23c45e1 https://github.com/skupperproject/skupper-router/actions/runs/4722038931/jobs/8405218428#step:5:52

In that range, there is only one commit, actually https://github.com/apache/qpid-proton/compare/6424d...23c45e1

**Comment by ganeshmurthy** [comment]
I am on the latest F37 (did a dnf update) and I am able to reproduce this issue without Andrew's change.

**Comment by jiridanek** [comment]
Fedora 38 running the tests also had some issues, maybe even ncat related if i recall corectly, same as ubuntu Jammy

* https://github.com/skupperproject/skupper-router/pull/1008
* https://github.com/skupperproject/skupper-router/pull/498

**Comment by jiridanek** [comment]
@ganeshmurthy do you also want to close this one as a duplicate?

* https://github.com/skupperproject/skupper-router/issues/1263

**Comment by ganeshmurthy** [comment]
> maybe not exact duplicate, but a lot similar

https://github.com/skupperproject/skupper-router/commit/7b20f192ac67555a3f30a74d02c4eb7403e5e1a8 fixed this issue but since the commit message was not correct, this issue did not automatically get closed. Closing this now.
