### ISSUE TITLE
test_h2spec' panicked at 'called `Result::unwrap()` on an `Err` value: DockerResponseServerError { status_code: 500, message: "error configuring network namespace for container 4f8f17d1xxx: CNI network \"test_h2spec_network\" not found" }', tests/testcontainers/docker.rs:185:89

### ISSUE THREAD

**Issue by jiridanek** [skupperproject/skupper-router#1139]
https://github.com/skupperproject/skupper-router/actions/runs/5357982375/jobs/9719627775?pr=1138#step:7:135

```
test testcontainers::test_skrouterd_sanity::test_skrouterd_sanity ... ok
thread 'testcontainers::test_h2spec::test_h2spec' panicked at 'called `Result::unwrap()` on an `Err` value: DockerResponseServerError { status_code: 500, message: "error configuring network namespace for container 4f8f17d15659a5be66a41b8a11faa55236b7b22eeb5451314bb0fd812493b73e: CNI network \"test_h2spec_network\" not found" }', tests/testcontainers/docker.rs:185:89
stack backtrace:
   0: rust_begin_unwind
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
   1: core::panicking::panic_fmt
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/result.rs:1687:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/result.rs:1089:23
   4: testcontainers::testcontainers::docker::create_and_start_container::{{closure}}
             at ./tests/testcontainers/docker.rs:185:5
```

**Comment by jiridanek** [comment]
This is something that I failed to reproduce. It seems to fail every time in CI. As far as I can tell, nothing of significance has changed in the CI environment since the time the test was passing fine.

My best guess at the moment is a timing issue, that is, if a podman network is created and a new container is put onto the network too soon after, then starting the container may possibly fail with an error like this.

I will try to put a sleep into the test, and if it helps, I'll either try to upgrade podman (GHA has a bit older version) or put in some retry for starting the container.

**Comment by jiridanek** [comment]
This sounds a lot like

* https://github.com/containers/podman/issues/7808
* https://github.com/containers/podman/issues/9472

and possibly this more complicated racy behaviour in

* https://github.com/containers/podman/issues/9451

So, upgrading to latest podman which does not seem to exhibit this race seems most correct solution to me. If it reoccurs, I would consider adding some retry, somewhere, but it would be best to be without it, if at all possible.
