### ISSUE TITLE
system_tests_open_properties test failure in test_02_verify_connector_properties

### ISSUE THREAD

**Issue by ganeshmurthy** [skupperproject/skupper-router#118]
```
::OpenPropertiesConfigTest::test_02_verify_connector_properties FAILED
::OpenPropertiesQdManageTest::test_01_verify_listener_properties PASSED
::OpenPropertiesQdManageTest::test_02_verify_connector_properties PASSED
::OpenPropertiesBadConfigTest::test_01_invalid_properties_check PASSED
::OpenPropertiesBadConfigTest::test_02_invalid_role_check PASSEDException in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 937, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 885, in run
    self._target(*self._args, **self._kwargs)
  File "/home/runner/work/skupper-router/skupper-router/skupper-router/tests/test_broker.py", line 113, in _main
    while self._container.process():
  File "/usr/local/lib64/python3.6/site-packages/proton/_reactor.py", line 257, in process
    event.dispatch(handler)
  File "/usr/local/lib64/python3.6/site-packages/proton/_events.py", line 164, in dispatch
    self.dispatch(h, type)
  File "/usr/local/lib64/python3.6/site-packages/proton/_events.py", line 164, in dispatch
    self.dispatch(h, type)
  File "/usr/local/lib64/python3.6/site-packages/proton/_events.py", line 161, in dispatch
    _dispatch(handler, type.method, self)
  File "/usr/local/lib64/python3.6/site-packages/proton/_events.py", line 128, in _dispatch
    m(*args)
  File "/usr/local/lib64/python3.6/site-packages/proton/_handlers.py", line 431, in on_connection_local_open
    self.on_connection_opened(event)
  File "/usr/local/lib64/python3.6/site-packages/proton/_handlers.py", line 471, in on_connection_opened
    _dispatch(self.delegate, 'on_connection_opened', event)
  File "/usr/local/lib64/python3.6/site-packages/proton/_events.py", line 128, in _dispatch
    m(*args)
  File "/home/runner/work/skupper-router/skupper-router/skupper-router/tests/system_tests_open_properties.py", line 54, in on_connection_opened
    self.open_properties = strip_default_options(event.connection.remote_properties)
  File "/home/runner/work/skupper-router/skupper-router/skupper-router/tests/system_tests_open_properties.py", line 37, in strip_default_options
    del options[key]
TypeError: 'NoneType' object does not support item deletion
```

https://github.com/skupperproject/skupper-router/runs/5397741867?check_suite_focus=true#step:27:423

**Comment by jiridanek** [comment]
Again, here https://github.com/jiridanek/skupper-router/runs/5426596691?check_suite_focus=true#step:27:12792

**Comment by ganeshmurthy** [comment]
Closing this issue since we have not seen this in over two years
