### ISSUE TITLE
Router crash on system_tests_one_router

### ISSUE THREAD

**Issue by ganeshmurthy** [skupperproject/skupper-router#1230]
```
[New LWP 3207]
[New LWP 3212]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `skrouterd -c test-router.conf -I /home/runner/work/skupper-router/skupper-route'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  sys_atomic_get (ref=0x9999999999999ecd) at /home/runner/work/skupper-router/skupper-router/skupper-router/include/qpid/dispatch/atomic.h:58
58	    return atomic_load(ref);
[Current thread is 1 (Thread 0x7ffb232c0700 (LWP 3215))]

Thread 7 (Thread 0x7ffb262c3700 (LWP 3212)):
#0  0x00007ffb306fb45c in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x00007ffb2fa0b0eb in suspend (ts=0x2b58be0, p=0x27eb8f0) at /home/runner/work/skupper-router/skupper-router/qpid-proton/c/src/proactor/epoll.c:401
#2  next_event_batch (p=0x27eb8f0, can_block=true) at /home/runner/work/skupper-router/skupper-router/qpid-proton/c/src/proactor/epoll.c:2503
#3  0x000000000042ff69 in thread_run (arg=<optimized out>) at /home/runner/work/skupper-router/skupper-router/skupper-router/src/server.c:1117
#4  thread_run (arg=<optimized out>, arg=<optimized out>) at /home/runner/work/skupper-router/skupper-router/skupper-router/src/server.c:1110
#5  0x00007ffb306f51ca in start_thread () from /lib64/libpthread.so.0
#6  0x00007ffb2e7b3e73 in clone () from /lib64/libc.so.6

Thread 6 (Thread 0x7ffb272c4700 (LWP 3207)):
#0  0x00007ffb306fb45c in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x0000000000473b39 in sys_cond_wait (cond=<optimized out>, held_mutex=<optimized out>, cond=<optimized out>, held_mutex=<optimized out>) at /home/runner/work/skupper-router/skupper-router/skupper-router/src/posix/threading.c:81
#2  0x0000000000447f7c in router_core_thread (arg=0x292ec60) at /home/runner/work/skupper-router/skupper-router/skupper-router/src/router_core/router_core_thread.c:228
#3  0x00007ffb306f51ca in start_thread () from /lib64/libpthread.so.0
#4  0x00007ffb2e7b3e73 in clone () from /lib64/libc.so.6

Thread 5 (Thread 0x7ffb282c5700 (LWP 3206)):
#0  0x00007ffb306fb45c in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x0000000000473b39 in sys_cond_wait (cond=<optimized out>, held_mutex=<optimized out>, cond=<optimized out>, held_mutex=<optimized out>) at /home/runner/work/skupper-router/skupper-router/skupper-router/src/posix/threading.c:81
#2  0x000000000046d214 in _vflow_thread_TH (context=0x292ec60) at /home/runner/work/skupper-router/skupper-router/skupper-router/src/vanflow.c:1303
#3  0x00007ffb306f51ca in start_thread () from /lib64/libpthread.so.0
#4  0x00007ffb2e7b3e73 in clone () from /lib64/libc.so.6

Thread 4 (Thread 0x7ffb242c1700 (LWP 3214)):
#0  0x00007ffb2e8a8f37 in epoll_wait () from /lib64/libc.so.6
#1  0x00007ffb2fa0b1f7 in poller_do_epoll (can_block=true, ts=0x2b1a7d0, p=0x27eb8f0) at /home/runner/work/skupper-router/skupper-router/qpid-proton/c/src/proactor/epoll.c:2547
#2  next_event_batch (p=0x27eb8f0, can_block=true) at /home/runner/work/skupper-router/skupper-router/qpid-proton/c/src/proactor/epoll.c:2486
#3  0x000000000042ff69 in thread_run (arg=<optimized out>) at /home/runner/work/skupper-router/skupper-router/skupper-router/src/server.c:1117
#4  thread_run (arg=<optimized out>, arg=<optimized out>) at /home/runner/work/skupper-router/skupper-router/skupper-router/src/server.c:1110
#5  0x00007ffb306f51ca in start_thread () from /lib64/libpthread.so.0
#6  0x00007ffb2e7b3e73 in clone () from /lib64/libc.so.6

Thread 3 (Thread 0x7ffb252c2700 (LWP 3213)):
#0  0x00007ffb306fb45c in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x00007ffb2fa0b0eb in suspend (ts=0x2b59d60, p=0x27eb8f0) at /home/runner/work/skupper-router/skupper-router/qpid-proton/c/src/proactor/epoll.c:401
#2  next_event_batch (p=0x27eb8f0, can_block=true) at /home/runner/work/skupper-router/skupper-router/qpid-proton/c/src/proactor/epoll.c:2503
#3  0x000000000042ff69 in thread_run (arg=<optimized out>) at /home/runner/work/skupper-router/skupper-router/skupper-router/src/server.c:1117
#4  thread_run (arg=<optimized out>, arg=<optimized out>) at /home/runner/work/skupper-router/skupper-router/skupper-router/src/server.c:1110
#5  0x00007ffb306f51ca in start_thread () from /lib64/libpthread.so.0
#6  0x00007ffb2e7b3e73 in clone () from /lib64/libc.so.6

Thread 2 (Thread 0x7ffb30d26340 (LWP 3193)):
#0  0x00007ffb306f66cd in __pthread_timedjoin_ex () from /lib64/libpthread.so.0
#1  0x000000000042e490 in qd_server_run (qd=<optimized out>) at /home/runner/work/skupper-router/skupper-router/skupper-router/src/server.c:1518
#2  0x00000000004ca150 in main_process (config_path=0x7ffc18edceba "test-router.conf", python_pkgdir=0x7ffc18edcece "/home/runner/work/skupper-router/skupper-router/skupper-router/python", test_hooks=<optimized out>, fd=2) at /home/runner/work/skupper-router/skupper-router/skupper-router/router/src/main.c:111
#3  0x0000000000429e84 in main (argc=5, argv=0x7ffc18edb528) at /home/runner/work/skupper-router/skupper-router/skupper-router/router/src/main.c:365

Thread 1 (Thread 0x7ffb232c0700 (LWP 3215)):
#0  sys_atomic_get (ref=0x9999999999999ecd) at /home/runner/work/skupper-router/skupper-router/skupper-router/include/qpid/dispatch/atomic.h:58
#1  qd_message_send_cut_through (msg=msg@entry=0x6ad9650, content=content@entry=0x9999999999999999, pnl=pnl@entry=0x3e29890, pns=pns@entry=0x60cf790, q3_stalled=q3_stalled@entry=0x7ffb232bf06f) at /home/runner/work/skupper-router/skupper-router/skupper-router/src/message.c:1865
#2  0x0000000000487ab9 in qd_message_send (in_msg=0x6ad9650, link=<optimized out>, ra_flags=0, q3_stalled=0x7ffb232bf06f) at /home/runner/work/skupper-router/skupper-router/skupper-router/src/message.c:1909
#3  0x000000000043542d in AMQP_conn_wake_handler (type_context=type_context@entry=0x290e2b0, conn=conn@entry=0x5697a90, context=context@entry=0x0) at /home/runner/work/skupper-router/skupper-router/skupper-router/src/router_node.c:396
#4  0x0000000000435879 in AMQP_link_flow_handler (context=0x290e2b0, link=0x2c3ed90) at /home/runner/work/skupper-router/skupper-router/skupper-router/src/router_node.c:1195
Undefined command: "py-bt".  Try "help".
#5  0x000000000042f392 in handle (qd_server=qd_server@entry=0x28381b0, e=e@entry=0x2aff6c0, pn_conn=pn_conn@entry=0x6054600, ctx=ctx@entry=0x5697a90) at /home/runner/work/skupper-router/skupper-router/skupper-router/src/server.c:1105
#6  0x000000000042ffc6 in thread_run (arg=<optimized out>) at /home/runner/work/skupper-router/skupper-router/skupper-router/src/server.c:1143
#7  thread_run (arg=<optimized out>, arg=<optimized out>) at /home/runner/work/skupper-router/skupper-router/skupper-router/src/server.c:1110
#8  0x00007ffb306f51ca in start_thread () from /lib64/libpthread.so.0
#9  0x00007ffb2e7b3e73 in clone () from /lib64/libc.so.6

Thread 7 (Thread 0x7ffb262c3700 (LWP 3212)):
```

https://github.com/ganeshmurthy/skupper-router/actions/runs/6303494328/job/17112845008#step:39:51

**Comment by ganeshmurthy** [comment]
This issue has already been fixed by https://github.com/skupperproject/skupper-router/commit/92c5ebd0e0ec8084500837fd3a01455a661bf33b
