### ISSUE TITLE
c_unittests failing with memory leak

### ISSUE THREAD

**Issue by ganeshmurthy** [skupperproject/skupper-router#1235]
```
2023-09-25T21:06:58.8533798Z 73: Direct leak of 56 byte(s) in 1 object(s) allocated from:
2023-09-25T21:06:58.8788635Z 73:     #0 0x7f923f7aa3d7 in __interceptor_malloc (/usr/lib64/clang/15.0.7/lib/linux/libclang_rt.asan-x86_64.so+0x10d3d7) (BuildId: 769dbb3986ba5b25cc74d55f32019dd39f9362b5)
2023-09-25T21:06:58.8790036Z 73:     #1 0x829efd in qd_malloc /home/runner/work/skupper-router/skupper-router/skupper-router/include/qpid/dispatch/ctools.h:225:17
2023-09-25T21:06:58.8790925Z 73:     #2 0x829efd in qdr_core_subscribe /home/runner/work/skupper-router/skupper-router/skupper-router/src/router_core/route_tables.c:147:31
2023-09-25T21:06:58.8791796Z 73:     #3 0x7551f7 in _vflow_init_address_watch_TH /home/runner/work/skupper-router/skupper-router/skupper-router/src/vanflow.c:1686:39
2023-09-25T21:06:58.8792620Z 73:     #4 0x75439f in _vflow_thread_TH /home/runner/work/skupper-router/skupper-router/skupper-router/src/vanflow.c:1315:17
2023-09-25T21:06:58.8793260Z 73:     #5 0x7f923e79815c in start_thread (/lib64/libc.so.6+0x8b15c) (BuildId: 23589836e284f381fbb26b9e8ca80ba5ed82e4da)
2023-09-25T21:06:58.8793653Z 73: 
2023-09-25T21:06:58.8794033Z 73: SUMMARY: AddressSanitizer: 56 byte(s) leaked in 1 allocation(s).
```

https://github.com/skupperproject/skupper-router/actions/runs/6304740269/job/17116740678?pr=1232#step:34:4085

**Comment by ganeshmurthy** [comment]
This is a duplicate of https://github.com/skupperproject/skupper-router/issues/989
Closing this
