### ISSUE TITLE
Invalid version error while compiling skupper-router on F38

### ISSUE THREAD

**Issue by ganeshmurthy** [skupperproject/skupper-router#1251]
```
copying build/lib/skupper_router_site.py -> /home/gmurthy/opensource/skupper-router/install/lib/python3.11/site-packages
skipping byte-compilation of /home/gmurthy/opensource/skupper-router/install/lib/python3.11/site-packages/skupper_router/__init__.py to __init__.cpython-311.pyc
skipping byte-compilation of /home/gmurthy/opensource/skupper-router/install/lib/python3.11/site-packages/skupper_router/management/__init__.py to __init__.cpython-311.pyc
skipping byte-compilation of /home/gmurthy/opensource/skupper-router/install/lib/python3.11/site-packages/skupper_router/management/entity.py to entity.cpython-311.pyc
skipping byte-compilation of /home/gmurthy/opensource/skupper-router/install/lib/python3.11/site-packages/skupper_router/management/error.py to error.cpython-311.pyc
skipping byte-compilation of /home/gmurthy/opensource/skupper-router/install/lib/python3.11/site-packages/skupper_router/management/client.py to client.cpython-311.pyc
byte-compiling /home/gmurthy/opensource/skupper-router/install/lib/python3.11/site-packages/skupper_router_site.py to skupper_router_site.cpython-311.pyc
running install_egg_info
/home/gmurthy/.local/lib/python3.11/site-packages/setuptools/command/egg_info.py:131: SetuptoolsDeprecationWarning: Invalid version: 'abf0523351acc25de50c9d15557847d0c679cd83(main)'.
!!

        ********************************************************************************
        Version 'abf0523351acc25de50c9d15557847d0c679cd83(main)' is not valid according to PEP 440.

        Please make sure to specify a valid version for your package.
        Also note that future releases of setuptools may halt the build process
        if an invalid version is given.

        This deprecation is overdue, please update your project and remove deprecated
        calls to avoid build errors in the future.

        See https://peps.python.org/pep-0440/ for details.
        ********************************************************************************

!!
  return _normalization.best_effort_version(tagged)
Traceback (most recent call last):
  File "/home/gmurthy/opensource/skupper-router/build/python/setup.py", line 48, in <module>
    setup(
  File "/home/gmurthy/.local/lib/python3.11/site-packages/setuptools/__init__.py", line 107, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gmurthy/.local/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
           ^^^^^^^^^^^^^^^^^^
  File "/home/gmurthy/.local/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/gmurthy/.local/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/home/gmurthy/.local/lib/python3.11/site-packages/setuptools/dist.py", line 1233, in run_command
    super().run_command(command)
  File "/home/gmurthy/.local/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/gmurthy/.local/lib/python3.11/site-packages/setuptools/command/install.py", line 78, in run
    return orig.install.run(self)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gmurthy/.local/lib/python3.11/site-packages/setuptools/_distutils/command/install.py", line 708, in run
    self.run_command(cmd_name)
  File "/home/gmurthy/.local/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/gmurthy/.local/lib/python3.11/site-packages/setuptools/dist.py", line 1233, in run_command
    super().run_command(command)
  File "/home/gmurthy/.local/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.ensure_finalized()
  File "/home/gmurthy/.local/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized
    self.finalize_options()
  File "/home/gmurthy/.local/lib/python3.11/site-packages/setuptools/command/install_egg_info.py", line 24, in finalize_options
    ei_cmd = self.get_finalized_command("egg_info")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gmurthy/.local/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 305, in get_finalized_command
    cmd_obj.ensure_finalized()
  File "/home/gmurthy/.local/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized
    self.finalize_options()
  File "/home/gmurthy/.local/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 225, in finalize_options
    parsed_version = packaging.version.Version(self.egg_version)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gmurthy/.local/lib/python3.11/site-packages/setuptools/_vendor/packaging/version.py", line 198, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
setuptools.extern.packaging.version.InvalidVersion: Invalid version: 'abf0523351acc25de50c9d15557847d0c679cd83-main-'
-- Up-to-date: /home/gmurthy/opensource/skupper-router/install/share/doc/skupper-router/skrouter.json
-- Up-to-date: /home/gmurthy/opensource/skupper-router/install/share/doc/skupper-router/skrouter.json.readme.txt
-- Installing: /home/gmurthy/opensource/skupper-router/install/sbin/skrouterd
-- Set runtime path of "/home/gmurthy/opensource/skupper-router/install/sbin/skrouterd" to "/usr/local/lib:/usr/local/lib64:/opt/qpid-proton/qpid-proton/lib64"

```

**Comment by jiridanek** [comment]
* duplicate of https://github.com/skupperproject/skupper-router/issues/973

**Comment by ganeshmurthy** [comment]
This issue has been fixed as part of fix to https://github.com/skupperproject/skupper-router/issues/1258
