### ISSUE TITLE
pip install fails on Ubuntu CI: invalid PEP440 version value

### ISSUE THREAD

**Issue by kgiusti** [skupperproject/skupper-router#1280]
See
https://github.com/skupperproject/skupper-router/actions/runs/6644764901/job/18083324713?pr=1275#step:17:369

```
Notice: e] A new release of pip is available: 23.0.1 -> 23.3.1
Notice: e] To update, run: pip install --upgrade pip
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Running command Getting requirements to build wheel
  configuration error: `project.version` must be pep440
  DESCRIPTION:
      The version of the project as supported by :pep:`440`.

  GIVEN VALUE:
      "8f3e2b9"

  OFFENDING RULE: 'format'

  DEFINITION:
      {
          "type": "string",
          "format": "pep440"
      }
  Traceback (most recent call last):
    File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-0lqglgxg/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-0lqglgxg/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-0lqglgxg/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 341, in run_setup
      exec(code, locals())
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-env-0lqglgxg/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 103, in setup
      return distutils.core.setup(**attrs)
    File "/tmp/pip-build-env-0lqglgxg/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 159, in setup
      dist.parse_config_files()
    File "/tmp/pip-build-env-0lqglgxg/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 653, in parse_config_files
      pyprojecttoml.apply_configuration(self, filename, ignore_option_errors)
    File "/tmp/pip-build-env-0lqglgxg/overlay/lib/python3.9/site-packages/setuptools/config/pyprojecttoml.py", line 66, in apply_configuration
      config = read_configuration(filepath, True, ignore_option_errors, dist)
    File "/tmp/pip-build-env-0lqglgxg/overlay/lib/python3.9/site-packages/setuptools/config/pyprojecttoml.py", line 127, in read_configuration
      validate(subset, filepath)
    File "/tmp/pip-build-env-0lqglgxg/overlay/lib/python3.9/site-packages/setuptools/config/pyprojecttoml.py", line 55, in validate
      raise ValueError(f"{error}\n{summary}") from None
  ValueError: invalid pyproject.toml config: `project.version`.
  configuration error: `project.version` must be pep440
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /opt/hostedtoolcache/Python/3.9.18/x64/bin/python3.9 /opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py get_requires_for_build_wheel /tmp/tmppfp2kuc3
  cwd: /home/runner/work/skupper-router/skupper-router/skupper-router/build/python
  Getting requirements to build wheel: finished with status 'error'
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

Notice:  A new release of pip is available: 23.0.1 -> 23.3.1
Notice:  To update, run: pip install --upgrade pip
CMake Error at python/cmake_install.cmake:50 (execute_process):
  execute_process failed command indexes:

    1: "Child return code: 1"

FAILED: CMakeFiles/install.util 
Call Stack (most recent call first):
  cmake_install.cmake:107 (include)


cd /home/runner/work/skupper-router/skupper-router/skupper-router/build && /usr/local/bin/cmake -P cmake_install.cmake
ninja: build stopped: subcommand failed.
```

**Comment by ganeshmurthy** [comment]
Fixed via https://github.com/skupperproject/skupper-router/commit/263f2a9fd63ae779a7f86f7d351feee62a3c775f
