### ISSUE TITLE
Direct leak of 3755 byte(s) in 50 object(s) allocated from:  #2 0x7f6c8a618728 in PyUnicode_New (/lib64/libpython3.12.so.1.0+0x1eb728)

### ISSUE THREAD

**Issue by jiridanek** [skupperproject/skupper-router#1347]
```
023-12-28T12:34:30.0282984Z 9: Direct leak of 3755 byte(s) in 50 object(s) allocated from:
2023-12-28T12:34:30.0284176Z 9:     #0 0x7f6c8ab562ef in malloc (/lib64/libasan.so.8+0xd92ef) (BuildId: 7fcb7759bc17ef47f9682414b6d99732d6a6ab0c)
2023-12-28T12:34:30.0285917Z 9:     #1 0x7f6c8a61075b  (/lib64/libpython3.12.so.1.0+0x1e375b) (BuildId: 77f2720b4a6d04c6896fabf45d54fda1d7cdcb27)
2023-12-28T12:34:30.0287954Z 9:     #2 0x7f6c8a618728 in PyUnicode_New (/lib64/libpython3.12.so.1.0+0x1eb728) (BuildId: 77f2720b4a6d04c6896fabf45d54fda1d7cdcb27)
2023-12-28T12:34:30.0289617Z 9:     #3 0x7f6c8a62c339  (/lib64/libpython3.12.so.1.0+0x1ff339) (BuildId: 77f2720b4a6d04c6896fabf45d54fda1d7cdcb27)
2023-12-28T12:34:30.0291289Z 9:     #4 0x7f6c8a6296b9  (/lib64/libpython3.12.so.1.0+0x1fc6b9) (BuildId: 77f2720b4a6d04c6896fabf45d54fda1d7cdcb27)
2023-12-28T12:34:30.0292810Z 9:     #5 0x7f6c8a629908  (/lib64/libpython3.12.so.1.0+0x1fc908) (BuildId: 77f2720b4a6d04c6896fabf45d54fda1d7cdcb27)
2023-12-28T12:34:30.0294322Z 9:     #6 0x7f6c8a6298d0  (/lib64/libpython3.12.so.1.0+0x1fc8d0) (BuildId: 77f2720b4a6d04c6896fabf45d54fda1d7cdcb27)
2023-12-28T12:34:30.0295875Z 9:     #7 0x7f6c8a629b1e  (/lib64/libpython3.12.so.1.0+0x1fcb1e) (BuildId: 77f2720b4a6d04c6896fabf45d54fda1d7cdcb27)
2023-12-28T12:34:30.0297470Z 9:     #8 0x7f6c8a6b89b8  (/lib64/libpython3.12.so.1.0+0x28b9b8) (BuildId: 77f2720b4a6d04c6896fabf45d54fda1d7cdcb27)
2023-12-28T12:34:30.0299051Z 9:     #9 0x7f6c8a6de1c9  (/lib64/libpython3.12.so.1.0+0x2b11c9) (BuildId: 77f2720b4a6d04c6896fabf45d54fda1d7cdcb27)
2023-12-28T12:34:30.0300786Z 9:     #10 0x7f6c8a54057a  (/lib64/libpython3.12.so.1.0+0x11357a) (BuildId: 77f2720b4a6d04c6896fabf45d54fda1d7cdcb27)
2023-12-28T12:34:30.0302316Z 9:     #11 0x7f6c8a63fcda  (/lib64/libpython3.12.so.1.0+0x212cda) (BuildId: 77f2720b4a6d04c6896fabf45d54fda1d7cdcb27)
2023-12-28T12:34:30.0304078Z 9:     #12 0x7f6c8a661ec9 in PyObject_CallMethodObjArgs (/lib64/libpython3.12.so.1.0+0x234ec9) (BuildId: 77f2720b4a6d04c6896fabf45d54fda1d7cdcb27)
2023-12-28T12:34:30.0306119Z 9:     #13 0x7f6c8a6617d1 in PyImport_ImportModuleLevelObject (/lib64/libpython3.12.so.1.0+0x2347d1) (BuildId: 77f2720b4a6d04c6896fabf45d54fda1d7cdcb27)
2023-12-28T12:34:30.0307919Z 9:     #14 0x7f6c8a5427b6  (/lib64/libpython3.12.so.1.0+0x1157b6) (BuildId: 77f2720b4a6d04c6896fabf45d54fda1d7cdcb27)
2023-12-28T12:34:30.0309589Z 9:     #15 0x7f6c8a6b8195 in PyEval_EvalCode (/lib64/libpython3.12.so.1.0+0x28b195) (BuildId: 77f2720b4a6d04c6896fabf45d54fda1d7cdcb27)
2023-12-28T12:34:30.0311274Z 9:     #16 0x7f6c8a6d31db  (/lib64/libpython3.12.so.1.0+0x2a61db) (BuildId: 77f2720b4a6d04c6896fabf45d54fda1d7cdcb27)
2023-12-28T12:34:30.0312923Z 9:     #17 0x7f6c8a63808b  (/lib64/libpython3.12.so.1.0+0x20b08b) (BuildId: 77f2720b4a6d04c6896fabf45d54fda1d7cdcb27)
2023-12-28T12:34:30.0314546Z 9:     #18 0x7f6c8a53d17a  (/lib64/libpython3.12.so.1.0+0x11017a) (BuildId: 77f2720b4a6d04c6896fabf45d54fda1d7cdcb27)
2023-12-28T12:34:30.0316108Z 9:     #19 0x7f6c8a63fcda  (/lib64/libpython3.12.so.1.0+0x212cda) (BuildId: 77f2720b4a6d04c6896fabf45d54fda1d7cdcb27)
2023-12-28T12:34:30.0317869Z 9:     #20 0x7f6c8a661ec9 in PyObject_CallMethodObjArgs (/lib64/libpython3.12.so.1.0+0x234ec9) (BuildId: 77f2720b4a6d04c6896fabf45d54fda1d7cdcb27)
2023-12-28T12:34:30.0319864Z 9:     #21 0x7f6c8a6617d1 in PyImport_ImportModuleLevelObject (/lib64/libpython3.12.so.1.0+0x2347d1) (BuildId: 77f2720b4a6d04c6896fabf45d54fda1d7cdcb27)
2023-12-28T12:34:30.0321663Z 9:     #22 0x7f6c8a66d54d  (/lib64/libpython3.12.so.1.0+0x24054d) (BuildId: 77f2720b4a6d04c6896fabf45d54fda1d7cdcb27)
2023-12-28T12:34:30.0323193Z 9:     #23 0x7f6c8a63808b  (/lib64/libpython3.12.so.1.0+0x20b08b) (BuildId: 77f2720b4a6d04c6896fabf45d54fda1d7cdcb27)
2023-12-28T12:34:30.0324703Z 9:     #24 0x7f6c8a620129  (/lib64/libpython3.12.so.1.0+0x1f3129) (BuildId: 77f2720b4a6d04c6896fabf45d54fda1d7cdcb27)
2023-12-28T12:34:30.0326446Z 9:     #25 0x7f6c8a620051 in PyObject_CallFunction (/lib64/libpython3.12.so.1.0+0x1f3051) (BuildId: 77f2720b4a6d04c6896fabf45d54fda1d7cdcb27)
2023-12-28T12:34:30.0328318Z 9:     #26 0x7f6c8a66d28f in PyImport_Import (/lib64/libpython3.12.so.1.0+0x24028f) (BuildId: 77f2720b4a6d04c6896fabf45d54fda1d7cdcb27)
2023-12-28T12:34:30.0330269Z 9:     #27 0x7f6c8a6d89bf in PyImport_ImportModule (/lib64/libpython3.12.so.1.0+0x2ab9bf) (BuildId: 77f2720b4a6d04c6896fabf45d54fda1d7cdcb27)
2023-12-28T12:34:30.0332917Z 9:     #28 0x5e6470 in qd_python_setup /home/runner/work/skupper-router/skupper-router/skupper-router/src/python_embedded.c:840
2023-12-28T12:34:30.0334883Z 9:     #29 0x56cf20 in qd_python_initialize /home/runner/work/skupper-router/skupper-router/skupper-router/src/python_embedded.c:58
2023-12-28T12:34:30.0336742Z 9:     #30 0x56cf20 in qd_dispatch /home/runner/work/skupper-router/skupper-router/skupper-router/src/dispatch.c:137
```

**Comment by jiridanek** [comment]
This should be a bug in Python itself, which is leaky

* https://github.com/skupperproject/skupper-router/issues/1360
