### ISSUE TITLE
Run python script '/home/runner/work/skupper-router/skupper-router/skupper-router/src/schema_c.py':ModuleNotFoundError: No module named 'skupper_router.management.entity'

### ISSUE THREAD

**Issue by jiridanek** [skupperproject/skupper-router#1350]
```
Traceback (most recent call last):
  File "/__w/skupper-router/skupper-router/skupper-router/build/tests/run.py", line 144, in <module>
Run python script '/home/runner/work/skupper-router/skupper-router/skupper-router/src/schema_c.py':ModuleNotFoundError: No module named 'skupper_router.management.entity'
    run_path(sys.argv[0], run_name="__main__")
  File "/__w/skupper-router/skupper-router/skupper-router/build/tests/run.py", line 127, in run_path
    runpy.run_path(file_path, run_name=run_name)
  File "/usr/lib64/python3.9/runpy.py", line 288, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/lib64/python3.9/runpy.py", line 97, in _run_module_code
/usr/bin/gcc -O2 -g  -flto -fno-fat-lto-objects -Wl,--export-dynamic -rdynamic "CMakeFiles/test-sender.dir/test-sender.c.o" -o test-sender  -Wl,-rpath,/__w/skupper-router/skupper-router/install/lib64 /__w/skupper-router/skupper-router/install/lib64/libqpid-proton.so.11.17.0 
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib64/python3.9/runpy.py", line [87](https://github.com/skupperproject/skupper-router/actions/runs/7355390523/job/20023930486?pr=1348#step:27:88), in _run_code
    exec(code, run_globals)
  File "/home/runner/work/skupper-router/skupper-router/skupper-router/src/schema_c.py", line 24, in <module>
    from skupper_router_internal.management.schema import EnumType
  File "/home/runner/work/skupper-router/skupper-router/skupper-router/python/skupper_router_internal/management/schema.py", line 32, in <module>
    from skupper_router.management.entity import EntityBase
ModuleNotFoundError: No module named 'skupper_router.management.entity'
```

https://github.com/skupperproject/skupper-router/actions/runs/7355390523/job/20023930486?pr=1348#step:27:85

**Comment by jiridanek** [comment]
This happens at random during build. It seems a flaky issue.

**Comment by jiridanek** [comment]
```
    raise ValueError("Failed to load data file skrouter.json")
```

https://github.com/skupperproject/skupper-router/actions/runs/7358938236/job/20032947714?pr=1358#step:27:99

**Comment by jiridanek** [comment]
Looks like an issue with parallel builds, something runs too soon before the files are in place?

**Comment by ganeshmurthy** [comment]
I am closing this issue. If we see this again, we will reopen.
