### ISSUE TITLE
TSAN is crashing in CI on ubuntu runs

### ISSUE THREAD

**Issue by kgiusti** [skupperproject/skupper-router#1503]
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f438aca1b9c in __tsan::Callback::Callback (pc=139928067742656, thr=0x7f437b2ade40, this=0x7f437b2ad470) at ../../../../src/libsanitizer/tsan/tsan_rtl_mutex.cpp:34

Thread 1 (Thread 0x7f437b36e640 (LWP 3253)):
Undefined command: "py-bt".  Try "help".
#0  0x00007f438aca1b9c in __tsan::Callback::Callback (pc=139928067742656, thr=0x7f437b2ade40, this=0x7f437b2ad470) at ../../../../src/libsanitizer/tsan/tsan_rtl_mutex.cpp:34
#1  __tsan::MutexPreLock (thr=thr@entry=0x7f437b2ade40, pc=pc@entry=139928067742656, addr=addr@entry=139928118854176, flagz=flagz@entry=0) at ../../../../src/libsanitizer/tsan/tsan_rtl_mutex.cpp:148
#2  0x00007f438ac59c39 in __interceptor_pthread_mutex_lock (m=m@entry=0x7f438dd18220 <trace_cache_pool>) at ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:4325
#3  0x00007f438dd0afc3 in _UIx86_64__mempool_free (object=0x7f438dc8cf20, pool=0x7f438dd18220 <trace_cache_pool>) at mi/mempool.c:179
#4  trace_cache_free (arg=0x7f438dc8cf20) at x86_64/Gtrace.c:72
#5  0x00007f438a491691 in __GI___nptl_deallocate_tsd () at ./nptl/nptl_deallocate_tsd.c:73
#6  __GI___nptl_deallocate_tsd () at ./nptl/nptl_deallocate_tsd.c:22
#7  0x00007f438a49494a in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:453
#8  0x00007f438a526850 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
```

**Comment by jiridanek** [comment]
@kgiusti the easiest thing may be to join the Ubuntu 24.04 public beta ;P https://github.blog/changelog/2024-05-14-github-hosted-runners-public-beta-of-ubuntu-24-04-is-now-available/ Newer compiler with newer tsan may not fail.
