### ISSUE TITLE
system_tests_delivery_counts still failing

### ISSUE THREAD

**Issue by jiridanek** [skupperproject/skupper-router#151]
reopen of https://github.com/skupperproject/skupper-router/issues/54 (note that here is different test, #54 was `test_06_large_message_released`)

```
41: =================================== FAILURES ===================================
41: __________ OneRouterLinkCountersTest.test_02_large_mesage_presettled ___________
41: 
41: self = <system_tests_delivery_counts.OneRouterLinkCountersTest testMethod=test_02_large_mesage_presettled>
41: 
41:     def test_02_large_mesage_presettled(self):
41: >       self.verify_presettled_count(True)
41: 
41: /home/runner/work/skupper-router/skupper-router/skupper-router/tests/system_tests_delivery_counts.py:1092: 
41: _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
41: /home/runner/work/skupper-router/skupper-router/skupper-router/tests/system_tests_delivery_counts.py:1023: in verify_presettled_count
41:     self.assertEqual(test.sender_stats['deliveryCount'], self.COUNT)
41: E   AssertionError: 36 != 40
```

https://github.com/skupperproject/skupper-router/runs/5488642947?check_suite_focus=true#step:9:4328

**Comment by jiridanek** [comment]
http://coprbe.devel.redhat.com/results/jdanek/skupper-router/rhel-8-s390x/00083972-skupper-router/builder-live.log.gz

```
======================================================================
FAIL: test_02_large_mesage_presettled (system_tests_delivery_counts.OneRouterLinkCountersTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/skupper-router/tests/system_tests_delivery_counts.py", line 1093, in test_02_large_mesage_presettled
    self.verify_presettled_count(True)
  File "/builddir/build/BUILD/skupper-router/tests/system_tests_delivery_counts.py", line 1024, in verify_presettled_count
    self.assertEqual(test.sender_stats['deliveryCount'], self.COUNT)
AssertionError: 33 != 40

----------------------------------------------------------------------
Ran 25 tests in 372.677s
```

**Comment by ganeshmurthy** [comment]
New failure
```
=========================================================================== FAILURES ===========================================================================
__________________________________________________ OneRouterLinkCountersTest.test_04_large_message_unsettled ___________________________________________________

self = <tests.system_tests_delivery_counts.OneRouterLinkCountersTest testMethod=test_04_large_message_unsettled>

    def test_04_large_message_unsettled(self):
>       self.verify_presettled_count(True)

/home/runner/work/skupper-router/skupper-router/skupper-router/tests/system_tests_delivery_counts.py:1102: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/home/runner/work/skupper-router/skupper-router/skupper-router/tests/system_tests_delivery_counts.py:1027: in verify_presettled_count
    self.assertEqual(test.sender_stats['deliveryCount'], self.COUNT)
E   AssertionError: 34 != 40
---------------------------------------------------------------------- Captured log call -----------------------------------------------------------------------
INFO     proton:_reactor.py:1052 Connecting to Url('amqp://0.0.0.0:24988')...
INFO     proton:_reactor.py:1090 Connected to 0.0.0.0
INFO     proton:_reactor.py:1104 Disconnected, already closed
----------------- generated xml file: /__w/skupper-router/skupper-router/skupper-router/build/tests/junitxmls/system_tests_delivery_counts.xml -----------------
=================================================================== short test summary info ====================================================================
FAILED ::OneRouterLinkCountersTest::test_04_large_message_unsettled - AssertionError: 34 != 40
=========================================================== 1 failed, 24 passed in 346.74s (0:05:46) ===========================================================
```
https://github.com/skupperproject/skupper-router/actions/runs/6667622545/job/18121437646#step:34:3925
