### ISSUE TITLE
timeout in system_tests_http1_adaptor

### ISSUE THREAD

**Issue by jiridanek** [skupperproject/skupper-router#152]
https://github.com/skupperproject/skupper-router/runs/5488621887?check_suite_focus=true#step:26:1804

```
58: ::Http1AdaptorBadEndpointsTest::test_01_unsolicited_response PASSED
58: ::Http1AdaptorBadEndpointsTest::test_02_bad_request_message FAILED
58: ::Http1AdaptorBadEndpointsTest::test_03_bad_response_message PASSED

[... some time later ...]

31/31 Test #58: system_tests_http1_adaptor ...........***Timeout 1200.13 sec
```

Router log (100MB uncompressed) [TestBadEndpoints.zip](https://github.com/skupperproject/skupper-router/files/8219166/TestBadEndpoints.zip)

**Comment by jiridanek** [comment]
This happened because `TestServer` instance leaked in the failed test. It has to be disposed even if test fails with AssertionError or some other exception.

**Comment by jiridanek** [comment]
https://github.com/skupperproject/skupper-router/runs/5870421205?check_suite_focus=true#step:26:2070

just a timeout (maybe the artifact zips do have something, I did not look)

**Comment by jiridanek** [comment]
http://coprbe.devel.redhat.com/results/jdanek/skupper-router/rhel-8-x86_64/00084043-skupper-router/builder-live.log.gz

```
67/67 Test #61: system_tests_http1_adaptor ..............***Timeout 600.01 sec
test_01_unsolicited_response (system_tests_http1_adaptor.Http1AdaptorBadEndpointsTest) ... ok
test_02_bad_request_message (system_tests_http1_adaptor.Http1AdaptorBadEndpointsTest) ... ok
test_03_bad_response_message (system_tests_http1_adaptor.Http1AdaptorBadEndpointsTest) ... ok
test_04_client_request_close (system_tests_http1_adaptor.Http1AdaptorBadEndpointsTest) ... ok
test_05_client_response_close (system_tests_http1_adaptor.Http1AdaptorBadEndpointsTest) ... ok
test_01_concurrent_requests (system_tests_http1_adaptor.Http1AdaptorEdge2EdgeTest) ... ok
test_02_credit_replenish (system_tests_http1_adaptor.Http1AdaptorEdge2EdgeTest) ... ok
test_03_server_reconnect (system_tests_http1_adaptor.Http1AdaptorEdge2EdgeTest) ... ok
test_04_server_pining_for_the_fjords (system_tests_http1_adaptor.Http1AdaptorEdge2EdgeTest) ... ok
test_05_large_streaming_msg (system_tests_http1_adaptor.Http1AdaptorEdge2EdgeTest) ... ok
test_1001_client_request_close (system_tests_http1_adaptor.Http1AdaptorEdge2EdgeTest) ... Exception in thread Thread-54:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 919, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 867, in run
    self._target(*self._args, **self._kwargs)
  File "/builddir/build/BUILD/skupper-router/tests/http1_tests.py", line 201, in _run
    rsp = client.getresponse()
  File "/usr/lib64/python3.6/http/client.py", line 1361, in getresponse
    response.begin()
  File "/usr/lib64/python3.6/http/client.py", line 311, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.6/http/client.py", line 272, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib64/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

ERROR
test_1002_client_response_close (system_tests_http1_adaptor.Http1AdaptorEdge2EdgeTest) ... WARNING:root:TestServer on port 27331 was not wait()'ed before
ERROR
test_2000_curl_get (system_tests_http1_adaptor.Http1AdaptorEdge2EdgeTest) ... WARNING:root:TestServer on port 27331 was not wait()'ed before
ERROR
test_2001_curl_put (system_tests_http1_adaptor.Http1AdaptorEdge2EdgeTest) ... WARNING:root:TestServer on port 27331 was not wait()'ed before
ERROR
test_2002_curl_post (system_tests_http1_adaptor.Http1AdaptorEdge2EdgeTest) ... WARNING:root:TestServer on port 27331 was not wait()'ed before
ERROR

Router EA2 debug dump file:
>>>>
alloc.c: Items of type 'qd_buffer_t' remain allocated at shutdown: 6 (SUPPRESSED)
alloc.c: Items of type 'qd_parsed_field_t' remain allocated at shutdown: 30 (SUPPRESSED)
alloc.c: Items of type 'qd_message_t' remain allocated at shutdown: 6 (SUPPRESSED)
alloc.c: Items of type 'qd_message_content_t' remain allocated at shutdown: 6 (SUPPRESSED)
alloc.c: Items of type 'qdr_delivery_t' remain allocated at shutdown: 6 (SUPPRESSED)
alloc.c: Items of type 'qd_link_ref_t' remain allocated at shutdown: 6 (SUPPRESSED)

<<<<
test_01_create_delete (system_tests_http1_adaptor.Http1AdaptorManagementTest)
Create and delete HTTP1 connectors and listeners.  The ... ok
test_01_delete_active_connector (system_tests_http1_adaptor.Http1AdaptorManagementTest)
Delete an HTTP1 connector that is currently connected to a server. ... ok
test_000_stats (system_tests_http1_adaptor.Http1AdaptorOneRouterTest) ... ok
test_001_get (system_tests_http1_adaptor.Http1AdaptorOneRouterTest) ... ok
test_002_head (system_tests_http1_adaptor.Http1AdaptorOneRouterTest) ... ok
test_003_post (system_tests_http1_adaptor.Http1AdaptorOneRouterTest) ... ok
test_004_put (system_tests_http1_adaptor.Http1AdaptorOneRouterTest) ... ok
test_005_get_10 (system_tests_http1_adaptor.Http1AdaptorOneRouterTest) ... ok
test_006_head_10 (system_tests_http1_adaptor.Http1AdaptorOneRouterTest) ... ok
test_007_post_10 (system_tests_http1_adaptor.Http1AdaptorOneRouterTest) ... ok
test_008_put_10 (system_tests_http1_adaptor.Http1AdaptorOneRouterTest) ... ok
test_01_backpressure_client (system_tests_http1_adaptor.Http1AdaptorQ2Standalone) ... ok
test_02_backpressure_server (system_tests_http1_adaptor.Http1AdaptorQ2Standalone) ... ok
/builddir/build/BUILD/skupper-router/tests/system_test.py:995: ResourceWarning: unclosed file <_io.BufferedWriter name=13>
  del cls.tester
/builddir/build/BUILD/skupper-router/tests/system_test.py:995: ResourceWarning: unclosed file <_io.BufferedWriter name=14>
  del cls.tester

======================================================================
ERROR: test_1001_client_request_close (system_tests_http1_adaptor.Http1AdaptorEdge2EdgeTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/skupper-router/tests/system_tests_http1_adaptor.py", line 412, in test_1001_client_request_close
    self.EA2.management)
  File "/builddir/build/BUILD/skupper-router/tests/http1_tests.py", line 1327, in client_request_close_test
    server.wait()
  File "/builddir/build/BUILD/skupper-router/tests/http1_tests.py", line 295, in wait
    self._send_shutdown_request()
  File "/builddir/build/BUILD/skupper-router/tests/http1_tests.py", line 322, in _send_shutdown_request
    with client.getresponse() as response:
  File "/usr/lib64/python3.6/http/client.py", line 1361, in getresponse
    response.begin()
  File "/usr/lib64/python3.6/http/client.py", line 311, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.6/http/client.py", line 272, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib64/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

======================================================================
ERROR: test_1002_client_response_close (system_tests_http1_adaptor.Http1AdaptorEdge2EdgeTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/skupper-router/tests/http1_tests.py", line 254, in new_server
    handler_cls=handler_cls)
  File "/builddir/build/BUILD/skupper-router/tests/http1_tests.py", line 272, in __init__
    tests)
  File "/builddir/build/BUILD/skupper-router/tests/http1_tests.py", line 138, in __init__
    super().__init__(addr, handler_cls)
  File "/usr/lib64/python3.6/socketserver.py", line 456, in __init__
    self.server_bind()
  File "/usr/lib64/python3.6/http/server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib64/python3.6/socketserver.py", line 470, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/builddir/build/BUILD/skupper-router/tests/system_tests_http1_adaptor.py", line 419, in test_1002_client_response_close
    self.http_listener11_port)
  File "/builddir/build/BUILD/skupper-router/tests/http1_tests.py", line 1373, in client_response_close_test
    tests=TESTS)
  File "/builddir/build/BUILD/skupper-router/tests/http1_tests.py", line 261, in new_server
    previous_server.wait(timeout=1)  # die quickly, we don't have a whole day
  File "/builddir/build/BUILD/skupper-router/tests/http1_tests.py", line 295, in wait
    self._send_shutdown_request()
  File "/builddir/build/BUILD/skupper-router/tests/http1_tests.py", line 322, in _send_shutdown_request
    with client.getresponse() as response:
  File "/usr/lib64/python3.6/http/client.py", line 1361, in getresponse
    response.begin()
  File "/usr/lib64/python3.6/http/client.py", line 311, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.6/http/client.py", line 272, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib64/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

======================================================================
ERROR: test_2000_curl_get (system_tests_http1_adaptor.Http1AdaptorEdge2EdgeTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/skupper-router/tests/http1_tests.py", line 254, in new_server
    handler_cls=handler_cls)
  File "/builddir/build/BUILD/skupper-router/tests/http1_tests.py", line 272, in __init__
    tests)
  File "/builddir/build/BUILD/skupper-router/tests/http1_tests.py", line 138, in __init__
    super().__init__(addr, handler_cls)
  File "/usr/lib64/python3.6/socketserver.py", line 456, in __init__
    self.server_bind()
  File "/usr/lib64/python3.6/http/server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib64/python3.6/socketserver.py", line 470, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/builddir/build/BUILD/skupper-router/tests/system_tests_http1_adaptor.py", line 426, in test_2000_curl_get
    self.http_server11_port)
  File "/builddir/build/BUILD/skupper-router/tests/http1_tests.py", line 1440, in curl_get_test
    server = TestServer.new_server(server_port, port, CURL_TESTS)
  File "/builddir/build/BUILD/skupper-router/tests/http1_tests.py", line 261, in new_server
    previous_server.wait(timeout=1)  # die quickly, we don't have a whole day
  File "/builddir/build/BUILD/skupper-router/tests/http1_tests.py", line 295, in wait
    self._send_shutdown_request()
  File "/builddir/build/BUILD/skupper-router/tests/http1_tests.py", line 322, in _send_shutdown_request
    with client.getresponse() as response:
  File "/usr/lib64/python3.6/http/client.py", line 1361, in getresponse
    response.begin()
  File "/usr/lib64/python3.6/http/client.py", line 311, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.6/http/client.py", line 272, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib64/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

======================================================================
ERROR: test_2001_curl_put (system_tests_http1_adaptor.Http1AdaptorEdge2EdgeTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/skupper-router/tests/http1_tests.py", line 254, in new_server
    handler_cls=handler_cls)
  File "/builddir/build/BUILD/skupper-router/tests/http1_tests.py", line 272, in __init__
    tests)
  File "/builddir/build/BUILD/skupper-router/tests/http1_tests.py", line 138, in __init__
    super().__init__(addr, handler_cls)
  File "/usr/lib64/python3.6/socketserver.py", line 456, in __init__
    self.server_bind()
  File "/usr/lib64/python3.6/http/server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib64/python3.6/socketserver.py", line 470, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/builddir/build/BUILD/skupper-router/tests/system_tests_http1_adaptor.py", line 433, in test_2001_curl_put
    self.http_server11_port)
  File "/builddir/build/BUILD/skupper-router/tests/http1_tests.py", line 1498, in curl_put_test
    server = TestServer.new_server(server_port, port, CURL_TESTS)
  File "/builddir/build/BUILD/skupper-router/tests/http1_tests.py", line 261, in new_server
    previous_server.wait(timeout=1)  # die quickly, we don't have a whole day
  File "/builddir/build/BUILD/skupper-router/tests/http1_tests.py", line 295, in wait
    self._send_shutdown_request()
  File "/builddir/build/BUILD/skupper-router/tests/http1_tests.py", line 322, in _send_shutdown_request
    with client.getresponse() as response:
  File "/usr/lib64/python3.6/http/client.py", line 1361, in getresponse
    response.begin()
  File "/usr/lib64/python3.6/http/client.py", line 311, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.6/http/client.py", line 272, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib64/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

======================================================================
ERROR: test_2002_curl_post (system_tests_http1_adaptor.Http1AdaptorEdge2EdgeTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/skupper-router/tests/http1_tests.py", line 254, in new_server
    handler_cls=handler_cls)
  File "/builddir/build/BUILD/skupper-router/tests/http1_tests.py", line 272, in __init__
    tests)
  File "/builddir/build/BUILD/skupper-router/tests/http1_tests.py", line 138, in __init__
    super().__init__(addr, handler_cls)
  File "/usr/lib64/python3.6/socketserver.py", line 456, in __init__
    self.server_bind()
  File "/usr/lib64/python3.6/http/server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib64/python3.6/socketserver.py", line 470, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/builddir/build/BUILD/skupper-router/tests/system_tests_http1_adaptor.py", line 440, in test_2002_curl_post
    self.http_server11_port)
  File "/builddir/build/BUILD/skupper-router/tests/http1_tests.py", line 1556, in curl_post_test
    server = TestServer.new_server(server_port, port, CURL_TESTS)
  File "/builddir/build/BUILD/skupper-router/tests/http1_tests.py", line 261, in new_server
    previous_server.wait(timeout=1)  # die quickly, we don't have a whole day
  File "/builddir/build/BUILD/skupper-router/tests/http1_tests.py", line 295, in wait
    self._send_shutdown_request()
  File "/builddir/build/BUILD/skupper-router/tests/http1_tests.py", line 322, in _send_shutdown_request
    with client.getresponse() as response:
  File "/usr/lib64/python3.6/http/client.py", line 1361, in getresponse
    response.begin()
  File "/usr/lib64/python3.6/http/client.py", line 311, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.6/http/client.py", line 272, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib64/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

----------------------------------------------------------------------
Ran 28 tests in 416.370s

FAILED (errors=5)


99% tests passed, 1 tests failed out of 67

Total Test time (real) = 1027.17 sec

The following tests FAILED:
	 61 - system_tests_http1_adaptor (Timeout)
```

**Comment by jiridanek** [comment]
on s390x https://app.travis-ci.com/github/jiridanek/skupper-router/jobs/569309906#L6772

```
66/67 Test #65: system_tests_address_watch ..............   Passed   36.96 sec
61: Simulate an HTTP client drop while sending a very large PUT ... Exception in thread Thread-54:
61: Traceback (most recent call last):
61:   File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
61:     self.run()
61:   File "/usr/lib/python3.8/threading.py", line 870, in run
61:     self._target(*self._args, **self._kwargs)
61:   File "/home/travis/build/jiridanek/skupper-router/tests/http1_tests.py", line 201, in _run
61:     rsp = client.getresponse()
61:   File "/usr/lib/python3.8/http/client.py", line 1332, in getresponse
61:     response.begin()
61:   File "/usr/lib/python3.8/http/client.py", line 303, in begin
61:     version, status, reason = self._read_status()
61:   File "/usr/lib/python3.8/http/client.py", line 264, in _read_status
61:     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
61:   File "/usr/lib/python3.8/socket.py", line 669, in readinto
61:     return self._sock.recv_into(b)
61: socket.timeout: timed out
67/67 Test #61: system_tests_http1_adaptor ..............***Timeout 500.09 sec
```

**Comment by kgiusti** [comment]
Fixed a test timing issue in test_1001_client_request_close (system_tests_http1_adaptor.Http1AdaptorEdge2EdgeTest) #536 

Doubt this timing issue is responsible for all of the issues reported in this bug so leaving this issue open.

**Comment by jiridanek** [comment]
https://github.com/skupperproject/skupper-router/runs/6724100344?check_suite_focus=true#step:26:2283

```
57: ::Http1AdaptorEdge2EdgeTest::test_1001_client_request_close FAILED
32/32 Test #57: system_tests_http1_adaptor ...........***Timeout 1200.09 sec
```

This is 2.0.x branch. It does not yet have the pytest-timeout PR, so there is no more output than this. But likely it is no different from the main failures.

**Comment by jiridanek** [comment]
Again, now on main, https://github.com/jiridanek/skupper-router/actions/runs/4392628238/jobs/7692667512#step:10:3356

```
58: ::Http1AdaptorBadEndpointsTest::test_06_bad_request_headers FAILED
58: ::Http1AdaptorBadEndpointsTest::test_07_bad_response_line FAILED
34/34 Test #58: system_tests_http1_adaptor ...........***Timeout 1199.76 sec
```

**Comment by jiridanek** [comment]
Once more, https://github.com/jiridanek/skupper-router/actions/runs/4392637181/jobs/7692727348#step:10:3339

**Comment by jiridanek** [comment]
And here Travis s390x https://app.travis-ci.com/github/jiridanek/skupper-router/jobs/597824513#L7887

hmm, I think I misspelled that as 360x at some point recently somewhere

**Comment by ganeshmurthy** [comment]
A year has passed since we last saw this. Closing
