### ISSUE TITLE
KeyError: 'owningAddr' in link['owningAddr'].endswith(service_address), links)

### ISSUE THREAD

**Issue by jiridanek** [skupperproject/skupper-router#1538]
Possibly related

* https://github.com/skupperproject/skupper-router/issues/1041#issuecomment-1494444565

```
======================================================================
ERROR: test_3000_N_client_pipeline_cancel (system_tests_http1_adaptor.Http1AdaptorEdge2EdgeTest.test_3000_N_client_pipeline_cancel)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/skupper-router-2.4.0.rc1/tests/system_tests_http1_adaptor.py", line 715, in test_3000_N_client_pipeline_cancel
    retry(lambda mg=EA2_mgmt, dc=index, loggie=logger:
  File "/builddir/build/BUILD/skupper-router-2.4.0.rc1/tests/system_test.py", line 191, in retry
    ret = function()
          ^^^^^^^^^^
  File "/builddir/build/BUILD/skupper-router-2.4.0.rc1/tests/system_tests_http1_adaptor.py", line 716, in <lambda>
    self._server_get_outstanding(mg, "testServer11", loggie) == dc,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/builddir/build/BUILD/skupper-router-2.4.0.rc1/tests/system_tests_http1_adaptor.py", line 625, in _server_get_outstanding
    for link in filtered:
  File "/builddir/build/BUILD/skupper-router-2.4.0.rc1/tests/system_tests_http1_adaptor.py", line 624, in <lambda>
    link['owningAddr'].endswith(service_address), links)
    ~~~~^^^^^^^^^^^^^^
KeyError: 'owningAddr'
```

https://github.com/skupperproject/skupper-router/pull/1537/checks?check_run_id=26617914387

https://download.copr.fedorainfracloud.org/results/packit/skupperproject-skupper-router-1537/fedora-40-x86_64/07662148-skupper-router/builder-live.log.gz

**Comment by ganeshmurthy** [comment]
Closing this issue since we have not seen this in CI for several months, will reopen if necessary
