### ISSUE TITLE
system_tests_two_routers test_17_address_wildcard local-idle-timeout expired

### ISSUE THREAD

**Issue by jiridanek** [skupperproject/skupper-router#207]
https://github.com/skupperproject/skupper-router/runs/5599813265?check_suite_focus=true#step:26:4852

```
28: ____________________ TwoRouterTest.test_17_address_wildcard ____________________
28: 
28: self = <system_tests_two_routers.TwoRouterTest testMethod=test_17_address_wildcard>
28: 
28:     def test_17_address_wildcard(self):
28:         # verify proper distribution is selected by wildcard
28:         addresses = [
28:             # (address, count of messages expected to be received)
28:             ('a.b.c.d',   1),  # closest 'a.b.c.d'
28:             ('b.c.d',     2),  # multi   '#.b.c.d'
28:             ('f.a.b.c.d', 2),  # multi   '#.b.c.d
28:             ('a.c.d',     2),  # multi   'a.*.d'
28:             ('a/c/c/d',   1),  # closest 'a/*/#.d
28:             ('a/x/z/z/d', 1),  # closest 'a/*/#.d
28:             ('a/x/d',     1),  # closest 'a.x.d'
28:             ('a.x.e',     1),  # balanced  ----
28:             ('m.b.c.d',   2)  # multi   '*/b/c/d'
28:         ]
28:     
28:         # two receivers per address - one for each router
28:         receivers = []
28:         for a in addresses:
28:             for x in range(2):
28:                 ar = AsyncTestReceiver(address=self.routers[x].addresses[0],
28:                                        source=a[0])
28:                 receivers.append(ar)
28:     
28:         # wait for the consumer info to propagate
28:         for a in addresses:
28: >           self.routers[0].wait_address(a[0], 1, 1)
```

```
28: self = <proton._utils.BlockingConnection object at 0x7fb0d73c2470>
28: event = PN_CONNECTION_REMOTE_CLOSE(<proton._endpoints.Connection 0x7fb0d72f7460 ~ 0x559441c87850>)
28: 
28:     def on_connection_remote_close(self, event: 'Event') -> None:
28:         """
28:         Event callback for when the link peer closes the connection.
28:         """
28:         if event.connection.state & Endpoint.LOCAL_ACTIVE:
28:             event.connection.close()
28:             if not self.closing:
28: >               raise ConnectionClosed(event.connection)
28: E               proton._utils.ConnectionClosed: Connection 0.0.0.0 closed due to: Condition('amqp:resource-limit-exceeded', 'local-idle-timeout expired')
```

This looks like a bug to me. Possibly in Proton's BlockingConnection? Idle timeout should never happen, empty frames should be sent automatically. And the machine is running tests with -j2, so it is not all that busy.

Router apparently did not fail in the test, at least I don't see any failures from router log printed in the output.

**Comment by jiridanek** [comment]
https://app.travis-ci.com/github/jiridanek/skupper-router/jobs/564430110#L7624

Very similar issue on Aarch64, but in different test

```
53: <<<<
53: ERROR:proton:Couldn't send: BrokenPipeError(32, 'Broken pipe')
57: 
57: Router Router8 output file:
57: >>>>
57: -----------------------------------------------------
57: Suppressions used:
57:   count      bytes template
57:       1         56 ^IoAdapter_init$
57:       1        288 ^pni_data_grow$
57:       2         96 ^pn_buffer$
57:       1         56 ^pn_object_new$
57:     654    1082266 /libpython3.*.so
57: -----------------------------------------------------
57: 
57: 
57: <<<<
53: 
53: Router RouterA output file:
53: >>>>
53: -----------------------------------------------------
53: Suppressions used:
53:   count      bytes template
53:       4        224 ^IoAdapter_init$
53:     731    1135010 /libpython3.*.so
53: -----------------------------------------------------
53: 
53: 
53: <<<<
53: 
53: ======================================================================
53: ERROR: test_06_parallel_priority (system_tests_router_mesh.ThreeRouterTest)
53: Create 10 senders each with a different priority.
53: ----------------------------------------------------------------------
53: Traceback (most recent call last):
53:   File "/home/travis/build/jiridanek/skupper-router/tests/system_tests_router_mesh.py", line 214, in test_06_parallel_priority
53:     self.RouterA.wait_address("closest/test_06_address")
53:   File "/home/travis/build/jiridanek/skupper-router/tests/system_test.py", line 679, in wait_address
53:     assert retry(check, **retry_kwargs)
53:   File "/home/travis/build/jiridanek/skupper-router/tests/system_test.py", line 142, in retry
53:     ret = function()
53:   File "/home/travis/build/jiridanek/skupper-router/tests/system_test.py", line 670, in check
53:     addrs = self.management.query(
53:   File "/home/travis/build/jiridanek/skupper-router/python/skupper_router/management/client.py", line 277, in query
53:     response = self.call(request)
53:   File "/home/travis/build/jiridanek/skupper-router/python/skupper_router/management/client.py", line 191, in call
53:     response = self.client.call(request)
53:   File "/home/travis/build/jiridanek/skupper-router/qpid-proton/python/proton/_utils.py", line 615, in call
53:     self.sender.send(request)
53:   File "/home/travis/build/jiridanek/skupper-router/qpid-proton/python/proton/_utils.py", line 140, in send
53:     self.connection.wait(lambda: _is_settled(delivery), msg="Sending on sender %s" % self.link.name,
53:   File "/home/travis/build/jiridanek/skupper-router/qpid-proton/python/proton/_utils.py", line 524, in wait
53:     self.container.process()
53:   File "/home/travis/build/jiridanek/skupper-router/qpid-proton/python/proton/_reactor.py", line 260, in process
53:     event.dispatch(handler)
53:   File "/home/travis/build/jiridanek/skupper-router/qpid-proton/python/proton/_events.py", line 158, in dispatch
53:     _dispatch(handler, type.method, self)
53:   File "/home/travis/build/jiridanek/skupper-router/qpid-proton/python/proton/_events.py", line 129, in _dispatch
53:     m(*args)
53:   File "/home/travis/build/jiridanek/skupper-router/qpid-proton/python/proton/_utils.py", line 552, in on_connection_remote_close
53:     raise ConnectionClosed(event.connection)
53: proton._utils.ConnectionClosed: Connection 0.0.0.0 closed due to: Condition('amqp:resource-limit-exceeded', 'local-idle-timeout expired')
53: 
53: ======================================================================
53: ERROR: test_06_parallel_priority (system_tests_router_mesh.ThreeRouterTest)
53: Create 10 senders each with a different priority.
53: ----------------------------------------------------------------------
53: Traceback (most recent call last):
53:   File "/home/travis/build/jiridanek/skupper-router/tests/system_test.py", line 933, in tearDown
53:     Tester.teardown(self)
53:   File "/home/travis/build/jiridanek/skupper-router/tests/system_test.py", line 874, in teardown
53:     raise RuntimeError("Errors during teardown: \n\n%s" % "\n\n".join([str(e) for e in errors]))
53: RuntimeError: Errors during teardown: 
53: 
53: Process 13265 error: still running
53: test-receiver -a 127.0.0.1:22739 -c 250 -s closest/test_06_address -d
53: /home/travis/build/jiridanek/skupper-router/build/tests/system_test.dir/system_tests_router_mesh/ThreeRouterTest/test_06_parallel_priority/test-receiver-43.cmd
53: >>>>
53: <<<<
53: 
53: ----------------------------------------------------------------------
53: Ran 6 tests in 168.842s
53: 
53: FAILED (errors=2)
56/64 Test #53: system_tests_router_mesh ................***Failed  168.97 sec
```

**Comment by ganeshmurthy** [comment]
Has not be reproduced in 2 years. Closing
