### ISSUE TITLE
system_tests_http1_adaptor Http1AdaptorEdge2EdgeTest::test_02_credit_replenish `AssertionError: 'client failed: Bad response code, expected 200 got 503' is not None`

### ISSUE THREAD

**Issue by jiridanek** [skupperproject/skupper-router#223]
https://download.copr.fedorainfracloud.org/results/jdanek/skupper-router/epel-8-x86_64/03820885-skupper-router/builder-live.log.gz

This failed once, and then passed upon rerun.

```
61/64 Test #60: system_tests_http1_adaptor ..............***Failed   55.01 sec
test_01_unsolicited_response (system_tests_http1_adaptor.Http1AdaptorBadEndpointsTest) ... ok
test_02_bad_request_message (system_tests_http1_adaptor.Http1AdaptorBadEndpointsTest) ... ok
test_03_bad_response_message (system_tests_http1_adaptor.Http1AdaptorBadEndpointsTest) ... ok
test_04_client_request_close (system_tests_http1_adaptor.Http1AdaptorBadEndpointsTest) ... ok
test_05_client_response_close (system_tests_http1_adaptor.Http1AdaptorBadEndpointsTest) ... ok
test_01_concurrent_requests (system_tests_http1_adaptor.Http1AdaptorEdge2EdgeTest) ... ok
test_02_credit_replenish (system_tests_http1_adaptor.Http1AdaptorEdge2EdgeTest) ... FAIL
test_03_server_reconnect (system_tests_http1_adaptor.Http1AdaptorEdge2EdgeTest) ... ok
test_04_server_pining_for_the_fjords (system_tests_http1_adaptor.Http1AdaptorEdge2EdgeTest) ... ok
test_05_large_streaming_msg (system_tests_http1_adaptor.Http1AdaptorEdge2EdgeTest) ... ok
test_1001_client_request_close (system_tests_http1_adaptor.Http1AdaptorEdge2EdgeTest) ... ok
test_1002_client_response_close (system_tests_http1_adaptor.Http1AdaptorEdge2EdgeTest) ... ok
test_2000_curl_get (system_tests_http1_adaptor.Http1AdaptorEdge2EdgeTest) ... ok
test_2001_curl_put (system_tests_http1_adaptor.Http1AdaptorEdge2EdgeTest) ... ok
test_2002_curl_post (system_tests_http1_adaptor.Http1AdaptorEdge2EdgeTest) ... ok
test_01_create_delete (system_tests_http1_adaptor.Http1AdaptorManagementTest)
Create and delete HTTP1 connectors and listeners.  The ... ok
test_01_delete_active_connector (system_tests_http1_adaptor.Http1AdaptorManagementTest)
Delete an HTTP1 connector that is currently connected to a server. ... ok
test_000_stats (system_tests_http1_adaptor.Http1AdaptorOneRouterTest) ... ok
test_001_get (system_tests_http1_adaptor.Http1AdaptorOneRouterTest) ... ok
test_002_head (system_tests_http1_adaptor.Http1AdaptorOneRouterTest) ... ok
test_003_post (system_tests_http1_adaptor.Http1AdaptorOneRouterTest) ... ok
test_004_put (system_tests_http1_adaptor.Http1AdaptorOneRouterTest) ... ok
test_005_get_10 (system_tests_http1_adaptor.Http1AdaptorOneRouterTest) ... ok
test_006_head_10 (system_tests_http1_adaptor.Http1AdaptorOneRouterTest) ... ok
test_007_post_10 (system_tests_http1_adaptor.Http1AdaptorOneRouterTest) ... ok
test_008_put_10 (system_tests_http1_adaptor.Http1AdaptorOneRouterTest) ... ok

Router INT.A debug dump file:
>>>>
alloc.c: Items of type 'qd_iterator_t' remain allocated at shutdown: 1 (SUPPRESSED)
alloc.c: Items of type 'qd_buffer_t' remain allocated at shutdown: 2 (SUPPRESSED)
alloc.c: Items of type 'qd_message_t' remain allocated at shutdown: 1 (SUPPRESSED)
alloc.c: Items of type 'qd_message_content_t' remain allocated at shutdown: 1 (SUPPRESSED)
alloc.c: Items of type 'qdr_delivery_t' remain allocated at shutdown: 1 (SUPPRESSED)

<<<<
test_01_backpressure_client (system_tests_http1_adaptor.Http1AdaptorQ2Standalone) ... ok
test_02_backpressure_server (system_tests_http1_adaptor.Http1AdaptorQ2Standalone) ... ok

======================================================================
FAIL: test_02_credit_replenish (system_tests_http1_adaptor.Http1AdaptorEdge2EdgeTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/skupper-router/tests/http1_tests.py", line 593, in test_02_credit_replenish
    self.assertIsNone(client.error)
AssertionError: 'client failed: Bad response code, expected 200 got 503' is not None

----------------------------------------------------------------------
Ran 28 tests in 54.839s

FAILED (failures=1)

      Start 63: system_tests_heartbeats
62/64 Test #62: system_tests_tcp_adaptor ................   Passed   40.18 sec
      Start 64: c_unittests
63/64 Test #64: c_unittests .............................   Passed    0.69 sec
64/64 Test #63: system_tests_heartbeats .................   Passed   26.37 sec

98% tests passed, 1 tests failed out of 64

Total Test time (real) = 500.04 sec

The following tests FAILED:
	 60 - system_tests_http1_adaptor (Failed)
Errors while running CTest
```

**Comment by jiridanek** [comment]
Here's a similar python stack trace on s390x

https://download.copr.fedorainfracloud.org/results/jdanek/skupper-router/fedora-rawhide-s390x/03821395-skupper-router/builder-live.log.gz

```
======================================================================
FAIL: test_03_server_reconnect (system_tests_http1_over_tcp.Http1OverTcpEdge2EdgeTest)
Verify server reconnect logic.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/skupper-router/tests/http1_tests.py", line 624, in test_03_server_reconnect
    self.assertIsNone(client.error)
AssertionError: 'client failed: Bad response code, expected 200 got 503' is not None

----------------------------------------------------------------------
```

**Comment by jiridanek** [comment]
https://download.copr.fedorainfracloud.org/results/jdanek/skupper-router/epel-8-s390x/04212482-skupper-router/builder-live.log.gz

**Comment by jiridanek** [comment]
Could be a duplicate of https://github.com/skupperproject/skupper-router/issues/303, or at least have common cause.

**Comment by kgiusti** [comment]
@jiridanek yeah I think you're correct that it's a dup of #303
