### ISSUE TITLE
Various `undefined-behavior` warnings and a final segfault from system_tests_tcp_adaptor

### ISSUE THREAD

**Issue by jiridanek** [skupperproject/skupper-router#230]
https://github.com/skupperproject/skupper-router/runs/5667753671?check_suite_focus=true#step:26:3478

```
59: SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/runner/work/skupper-router/skupper-router/qpid-proton/c/src/proactor/epoll_raw_connection.c:254:22 in 
59: /home/runner/work/skupper-router/skupper-router/qpid-proton/c/src/proactor/epoll_raw_connection.c:256:10: runtime error: pointer index expression with base 0xffffffffffffff40 overflowed to 0x000000000480
59:     #0 0x7f8a3ad84827 in pn_raw_connection_local_addr /home/runner/work/skupper-router/skupper-router/qpid-proton/c/src/proactor/epoll_raw_connection.c:256
59:     #1 0x4a1e44 in qdr_tcp_connection_egress /home/runner/work/skupper-router/skupper-router/skupper-router/src/adaptors/tcp_adaptor.c:1124
59:     #2 0x4b41f9 in qdr_tcp_deliver /home/runner/work/skupper-router/skupper-router/skupper-router/src/adaptors/tcp_adaptor.c:1655
59:     #3 0x622416 in qdr_link_process_deliveries /home/runner/work/skupper-router/skupper-router/skupper-router/src/router_core/transfer.c:194
59:     #4 0x59a5e1 in qdr_connection_process /home/runner/work/skupper-router/skupper-router/skupper-router/src/router_core/connections.c:401
59:     #5 0x4aa011 in on_activate /home/runner/work/skupper-router/skupper-router/skupper-router/src/adaptors/tcp_adaptor.c:200
59:     #6 0x6833e6 in qd_timer_visit /home/runner/work/skupper-router/skupper-router/skupper-router/src/timer.c:320
59:     #7 0x674076 in handle /home/runner/work/skupper-router/skupper-router/skupper-router/src/server.c:980
59:     #8 0x67b975 in thread_run /home/runner/work/skupper-router/skupper-router/skupper-router/src/server.c:1095
59:     #9 0x7f8a39900b19 in start_thread (/lib64/libc.so.6+0x8db19)
59:     #10 0x7f8a3998565f in __GI___clone3 (/lib64/libc.so.6+0x11265f)
59: 
59: SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/runner/work/skupper-router/skupper-router/qpid-proton/c/src/proactor/epoll_raw_connection.c:256:10 in 
59: AddressSanitizer:DEADLYSIGNAL
59: =================================================================
59: ==2637==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000480 (pc 0x7f8a3ad87d2e bp 0x7f8a2e621840 sp 0x7f8a2e621830 T4)
59: ==2637==The signal is caused by a READ memory access.
59: ==2637==Hint: address points to the zero page.
59:     #0 0x7f8a3ad87d2e in pn_netaddr_socklen /home/runner/work/skupper-router/skupper-router/qpid-proton/c/src/proactor/netaddr-internal.c:55
59:     #1 0x7f8a3ad8a515 in pn_netaddr_host_port /home/runner/work/skupper-router/skupper-router/qpid-proton/c/src/proactor/netaddr-internal.c:74
59:     #2 0x4a1e72 in qdr_tcp_connection_egress /home/runner/work/skupper-router/skupper-router/skupper-router/src/adaptors/tcp_adaptor.c:1127
59:     #3 0x4b41f9 in qdr_tcp_deliver /home/runner/work/skupper-router/skupper-router/skupper-router/src/adaptors/tcp_adaptor.c:1655
59:     #4 0x622416 in qdr_link_process_deliveries /home/runner/work/skupper-router/skupper-router/skupper-router/src/router_core/transfer.c:194
59:     #5 0x59a5e1 in qdr_connection_process /home/runner/work/skupper-router/skupper-router/skupper-router/src/router_core/connections.c:401
59:     #6 0x4aa011 in on_activate /home/runner/work/skupper-router/skupper-router/skupper-router/src/adaptors/tcp_adaptor.c:200
59:     #7 0x6833e6 in qd_timer_visit /home/runner/work/skupper-router/skupper-router/skupper-router/src/timer.c:320
59:     #8 0x674076 in handle /home/runner/work/skupper-router/skupper-router/skupper-router/src/server.c:980
59:     #9 0x67b975 in thread_run /home/runner/work/skupper-router/skupper-router/skupper-router/src/server.c:1095
59:     #10 0x7f8a39900b19 in start_thread (/lib64/libc.so.6+0x8db19)
59:     #11 0x7f8a3998565f in __GI___clone3 (/lib64/libc.so.6+0x11265f)
59: 
59: AddressSanitizer can not provide additional info.
59: SUMMARY: AddressSanitizer: SEGV /home/runner/work/skupper-router/skupper-router/qpid-proton/c/src/proactor/netaddr-internal.c:55 in pn_netaddr_socklen
59: Thread T4 created by T0 here:
59:     #0 0x7f8a3ae7f866 in pthread_create (/lib64/libasan.so.6+0x56866)
59:     #1 0x560e65 in sys_thread /home/runner/work/skupper-router/skupper-router/skupper-router/src/posix/threading.c:181
59:     #2 0x67deec in qd_server_run /home/runner/work/skupper-router/skupper-router/skupper-router/src/server.c:1489
59:     #3 0x432fed in main_process /home/runner/work/skupper-router/skupper-router/skupper-router/router/src/main.c:105
59:     #4 0x431ea2 in main /home/runner/work/skupper-router/skupper-router/skupper-router/router/src/main.c:359
59:     #5 0x7f8a398a055f in __libc_start_call_main (/lib64/libc.so.6+0x2d55f)
59: 
59: ==2637==ABORTING
```

```
59: Router EC2 output file:
59: >>>>
59: /home/runner/work/skupper-router/skupper-router/qpid-proton/c/src/proactor/epoll_raw_connection.c:254:22: runtime error: applying non-zero offset 18446744073709551424 to null pointer
59:     #0 0x7f8a3ad84816 in pn_raw_connection_local_addr /home/runner/work/skupper-router/skupper-router/qpid-proton/c/src/proactor/epoll_raw_connection.c:254
59:     #1 0x4a1e44 in qdr_tcp_connection_egress /home/runner/work/skupper-router/skupper-router/skupper-router/src/adaptors/tcp_adaptor.c:1124
59:     #2 0x4b41f9 in qdr_tcp_deliver /home/runner/work/skupper-router/skupper-router/skupper-router/src/adaptors/tcp_adaptor.c:1655
59:     #3 0x622416 in qdr_link_process_deliveries /home/runner/work/skupper-router/skupper-router/skupper-router/src/router_core/transfer.c:194
59:     #4 0x59a5e1 in qdr_connection_process /home/runner/work/skupper-router/skupper-router/skupper-router/src/router_core/connections.c:401
59:     #5 0x4aa011 in on_activate /home/runner/work/skupper-router/skupper-router/skupper-router/src/adaptors/tcp_adaptor.c:200
59:     #6 0x6833e6 in qd_timer_visit /home/runner/work/skupper-router/skupper-router/skupper-router/src/timer.c:320
59:     #7 0x674076 in handle /home/runner/work/skupper-router/skupper-router/skupper-router/src/server.c:980
59:     #8 0x67b975 in thread_run /home/runner/work/skupper-router/skupper-router/skupper-router/src/server.c:1095
59:     #9 0x7f8a39900b19 in start_thread (/lib64/libc.so.6+0x8db19)
59:     #10 0x7f8a3998565f in __GI___clone3 (/lib64/libc.so.6+0x11265f)
```

**Comment by jiridanek** [comment]
The test also seems to repeat a proton DEBUG log line at the end, until GHA cuts it off for producing too much output, similarly to https://github.com/skupperproject/skupper-router/issues/225.

**Comment by jiridanek** [comment]
This fail looks quite rare in CI. Here's only second example where I saw it https://github.com/jiridanek/skupper-router/runs/5698747118?check_suite_focus=true#step:9:3774

**Comment by jiridanek** [comment]
https://github.com/skupperproject/skupper-router/runs/5832866904?check_suite_focus=true

```
2022-04-05T12:03:40.2011056Z 59:         if errors:
2022-04-05T12:03:40.2011353Z 59: >           raise RuntimeError("Errors during teardown: \n\n%s" % "\n\n".join([str(e) for e in errors]))
2022-04-05T12:03:40.2011694Z 59: E           RuntimeError: Errors during teardown: 
2022-04-05T12:03:40.2011933Z 59: E           
2022-04-05T12:03:40.2012244Z 59: E           Process 3669 error: exit code 66, expected -1
2022-04-05T12:03:40.2012911Z 59: E           skrouterd -c INTA.conf -I /home/runner/work/skupper-router/skupper-router/skupper-router/python
2022-04-05T12:03:40.2013898Z 59: E           /__w/skupper-router/skupper-router/skupper-router/build/tests/system_test.dir/system_tests_tcp_adaptor/TcpAdaptor/setUpClass/INTA-1.cmd
2022-04-05T12:03:40.2014248Z 59: E           >>>>
2022-04-05T12:03:40.2014481Z 59: E           ThreadSanitizer:DEADLYSIGNAL
2022-04-05T12:03:40.2015017Z 59: E           ==3669==ERROR: ThreadSanitizer: SEGV on unknown address 0x000000000480 (pc 0x7f8724c32f36 bp 0x7f8717fc2e80 sp 0x7f8717fc2e70 T3673)
2022-04-05T12:03:40.2015384Z 59: E           ==3669==The signal is caused by a READ memory access.
2022-04-05T12:03:40.2015686Z 59: E           ==3669==Hint: address points to the zero page.
2022-04-05T12:03:40.2016783Z 59: E               #0 pn_netaddr_socklen /home/runner/work/skupper-router/skupper-router/qpid-proton/c/src/proactor/netaddr-internal.c:55 (libqpid-proton-proactor.so.1+0xef36)
2022-04-05T12:03:40.2017619Z 59: E               #1 pn_netaddr_host_port /home/runner/work/skupper-router/skupper-router/qpid-proton/c/src/proactor/netaddr-internal.c:74 (libqpid-proton-proactor.so.1+0xf871)
2022-04-05T12:03:40.2018530Z 59: E               #2 qdr_tcp_connection_egress /home/runner/work/skupper-router/skupper-router/skupper-router/src/adaptors/tcp_adaptor.c:1126 (skrouterd+0x44825c)
2022-04-05T12:03:40.2019215Z 59: E               #3 qdr_tcp_deliver /home/runner/work/skupper-router/skupper-router/skupper-router/src/adaptors/tcp_adaptor.c:1654 (skrouterd+0x448960)
2022-04-05T12:03:40.2019903Z 59: E               #4 qdr_link_process_deliveries /home/runner/work/skupper-router/skupper-router/skupper-router/src/router_core/transfer.c:180 (skrouterd+0x4b1500)
2022-04-05T12:03:40.2020733Z 59: E               #5 qdr_tcp_push /home/runner/work/skupper-router/skupper-router/skupper-router/src/adaptors/tcp_adaptor.c:1583 (skrouterd+0x443ff5)
2022-04-05T12:03:40.2021419Z 59: E               #6 qdr_connection_process /home/runner/work/skupper-router/skupper-router/skupper-router/src/router_core/connections.c:401 (skrouterd+0x48f9d2)
2022-04-05T12:03:40.2022094Z 59: E               #7 on_activate /home/runner/work/skupper-router/skupper-router/skupper-router/src/adaptors/tcp_adaptor.c:200 (skrouterd+0x448d21)
2022-04-05T12:03:40.2022826Z 59: E               #8 qd_timer_visit /home/runner/work/skupper-router/skupper-router/skupper-router/src/timer.c:320 (skrouterd+0x4cd5cf)
2022-04-05T12:03:40.2023415Z 59: E               #9 handle /home/runner/work/skupper-router/skupper-router/skupper-router/src/server.c:980 (skrouterd+0x4c8e9e)
2022-04-05T12:03:40.2023997Z 59: E               #10 thread_run /home/runner/work/skupper-router/skupper-router/skupper-router/src/server.c:1095 (skrouterd+0x4caca7)
2022-04-05T12:03:40.2024767Z 59: E               #11 _thread_init /home/runner/work/skupper-router/skupper-router/skupper-router/src/posix/threading.c:172 (skrouterd+0x47da7d)
2022-04-05T12:03:40.2025181Z 59: E               #12 __tsan_thread_start_func <null> (libtsan.so.0+0x2f54f)
2022-04-05T12:03:40.2025490Z 59: E               #13 start_thread <null> (libc.so.6+0x8db19)
2022-04-05T12:03:40.2025772Z 59: E               #14 __GI___clone3 <null> (libc.so.6+0x11265f)
2022-04-05T12:03:40.2026002Z 59: E           
2022-04-05T12:03:40.2026378Z 59: E           ThreadSanitizer can not provide additional info.
2022-04-05T12:03:40.2027003Z 59: E           SUMMARY: ThreadSanitizer: SEGV /home/runner/work/skupper-router/skupper-router/qpid-proton/c/src/proactor/netaddr-internal.c:55 in pn_netaddr_socklen
2022-04-05T12:03:40.2027391Z 59: E           ==3669==ABORTING
```

**Comment by kgiusti** [comment]
Likely the same bug is the cause of https://github.com/skupperproject/skupper-router/issues/269
