### ISSUE TITLE
c_benchmarks test failing with use-after-poison error

### ISSUE THREAD

**Issue by ganeshmurthy** [skupperproject/skupper-router#231]
```
64: ==3401==ERROR: AddressSanitizer: use-after-poison on address 0x6190002f3b68 at pc 0x55e3afe830c9 bp 0x7f095fa28990 sp 0x7f095fa28980
64: READ of size 8 at 0x6190002f3b68 thread T29
64:     #0 0x55e3afe830c8 in qdr_tcp_connection_egress ../src/adaptors/tcp_adaptor.c:1124
64:     #1 0x55e3afe8cf99 in qdr_tcp_deliver ../src/adaptors/tcp_adaptor.c:1655
64:     #2 0x55e3b00312e4 in qdr_link_process_deliveries ../src/router_core/transfer.c:194
64:     #3 0x55e3afe8c3da in qdr_tcp_push ../src/adaptors/tcp_adaptor.c:1584
64:     #4 0x55e3aff8ff1b in qdr_connection_process ../src/router_core/connections.c:401
64:     #5 0x55e3afe7169a in on_activate ../src/adaptors/tcp_adaptor.c:200
64:     #6 0x55e3b00aa181 in qd_timer_visit ../src/timer.c:320
64:     #7 0x55e3b0098443 in handle ../src/server.c:980
64:     #8 0x55e3b009a0e3 in thread_run ../src/server.c:1095
64:     #9 0x55e3aff4bb05 in _thread_init ../src/posix/threading.c:172
64:     #10 0x7f096f4c2608 in start_thread /build/glibc-sMfBJT/glibc-2.31/nptl/pthread_create.c:477
64:     #11 0x7f096df70162 in __clone (/lib/x86_64-linux-gnu/libc.so.6+0x11f162)
64: 
64: 0x6190002f3b68 is located 232 bytes inside of 960-byte region [0x6190002f3a80,0x6190002f3e40)
64: allocated by thread T29 here:
64:     #0 0x7f096f638aa5 in posix_memalign (/lib/x86_64-linux-gnu/libasan.so.5+0x10eaa5)
64:     #1 0x55e3afe9b6c8 in qd_alloc ../src/alloc_pool.c:396
64:     #2 0x55e3afe70803 in new_qdr_tcp_connection_t ../src/adaptors/tcp_adaptor.c:125
64:     #3 0x55e3afe8191f in qdr_tcp_connection_egress ../src/adaptors/tcp_adaptor.c:1074
64:     #4 0x55e3afe8cf99 in qdr_tcp_deliver ../src/adaptors/tcp_adaptor.c:1655
64:     #5 0x55e3b00312e4 in qdr_link_process_deliveries ../src/router_core/transfer.c:194
64:     #6 0x55e3afe8c3da in qdr_tcp_push ../src/adaptors/tcp_adaptor.c:1584
64:     #7 0x55e3aff8ff1b in qdr_connection_process ../src/router_core/connections.c:401
64:     #8 0x55e3afe7169a in on_activate ../src/adaptors/tcp_adaptor.c:200
64:     #9 0x55e3b00aa181 in qd_timer_visit ../src/timer.c:320
64:     #10 0x55e3b0098443 in handle ../src/server.c:980
64:     #11 0x55e3b009a0e3 in thread_run ../src/server.c:1095
64:     #12 0x55e3aff4bb05 in _thread_init ../src/posix/threading.c:172
64:     #13 0x7f096f4c2608 in start_thread /build/glibc-sMfBJT/glibc-2.31/nptl/pthread_create.c:477
64: 64: Thread T29 created by T25 here:
64:     #0 0x7f096f564805 in pthread_create (/lib/x86_64-linux-gnu/libasan.so.5+0x3a805)
64:     #1 0x55e3aff4bc74 in sys_thread ../src/posix/threading.c:181
64:     #2 0x55e3b00a1b2b in qd_server_run ../src/server.c:1489
64:     #3 0x55e3b0112198 in QDR::run() const ../tests/c_benchmarks/../c_unittests/helpers.hpp:238
64:     #4 0x55e3b0115b20 in DispatchRouterThreadTCPLatencyTest::DispatchRouterThreadTCPLatencyTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)::{lambda()#1}::operator()() const ../tests/c_benchmarks/bm_tcp_adapter.cpp:240
64:     #5 0x55e3b011dade in void std::__invoke_impl<void, DispatchRouterThreadTCPLatencyTest::DispatchRouterThreadTCPLatencyTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)::{lambda()#1}>(std::__invoke_other, DispatchRouterThreadTCPLatencyTest::DispatchRouterThreadTCPLatencyTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)::{lambda()#1}&&) /usr/include/c++/9/bits/invoke.h:60
64:     #6 0x55e3b011d75b in std::__invoke_result<DispatchRouterThreadTCPLatencyTest::DispatchRouterThreadTCPLatencyTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)::{lambda()#1}>::type std::__invoke<DispatchRouterThreadTCPLatencyTest::DispatchRouterThreadTCPLatencyTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)::{lambda()#1}>(std::__invoke_result&&, (DispatchRouterThreadTCPLatencyTest::DispatchRouterThreadTCPLatencyTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)::{lambda()#1}&&)...) /usr/include/c++/9/bits/invoke.h:95
64:     #7 0x55e3b011d4ed in void std::thread::_Invoker<std::tuple<DispatchRouterThreadTCPLatencyTest::DispatchRouterThreadTCPLatencyTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)::{lambda()#1}> >::_M_invoke<0ul>(std::_Index_tuple<0ul>) /usr/include/c++/9/thread:244
64:     #8 0x55e3b011d2ca in std::thread::_Invoker<std::tuple<DispatchRouterThreadTCPLatencyTest::DispatchRouterThreadTCPLatencyTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)::{lambda()#1}> >::operator()() /usr/include/c++/9/thread:251
64:     #9 0x55e3b011d170 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<DispatchRouterThreadTCPLatencyTest::DispatchRouterThreadTCPLatencyTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)::{lambda()#1}> > >::_M_run() /usr/include/c++/9/thread:195
64:     #10 0x7f096eaa3de3  (/lib/x86_64-linux-gnu/libstdc++.so.6+0xd6de3)
64: 
64: Thread T25 created by T0 here:
64:     #0 0x7f096f564805 in pthread_create (/lib/x86_64-linux-gnu/libasan.so.5+0x3a805)
64:     #1 0x7f096eaa40a8 in std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)()) (/lib/x86_64-linux-gnu/libstdc++.so.6+0xd70a8)
64:     #2 0x55e3b0115eab in DispatchRouterThreadTCPLatencyTest::DispatchRouterThreadTCPLatencyTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) ../tests/c_benchmarks/bm_tcp_adapter.cpp:235
64:     #3 0x55e3b010f899 in BM_TCPEchoServerLatency1QDRThread ../tests/c_benchmarks/bm_tcp_adapter.cpp:298
64:     #4 0x7f096f51672e in benchmark::internal::BenchmarkInstance::Run(unsigned long, int, benchmark::internal::ThreadTimer*, benchmark::internal::ThreadManager*) const (/lib/x86_64-linux-gnu/libbenchmark.so.1+0x3972e)
64: 
64: SUMMARY: AddressSanitizer: use-after-poison ../src/adaptors/tcp_adaptor.c:1124 in qdr_tcp_connection_egress
64: Shadow bytes around the buggy address:
64:   0x0c3280056710: f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7
64:   0x0c3280056720: f7 f7 00 00 00 00 00 00 fa fa fa fa fa fa fa fa
64:   0x0c3280056730: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
64:   0x0c3280056740: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
64:   0x0c3280056750: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
64: =>0x0c3280056760: 00 00 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7[f7]f7 f7
64:   0x0c3280056770: f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7
64:   0x0c3280056780: f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7
64:   0x0c3280056790: f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7
64:   0x0c32800567a0: f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7
64:   0x0c32800567b0: f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7
64: Shadow byte legend (one shadow byte represents 8 application bytes):
64:   Addressable:           00
64:   Partially addressable: 01 02 03 04 05 06 07 
64:   Heap left redzone:       fa
64:   Freed heap region:       fd
64:   Stack left redzone:      f1
64:   Stack mid redzone:       f2
64:   Stack right redzone:     f3
64:   Stack after return:      f5
64:   Stack use after scope:   f8
64:   Global redzone:          f9
64:   Global init order:       f6
64:   Poisoned by user:        f7
64:   Container overflow:      fc
64:   Array cookie:            ac
64:   Intra object redzone:    bb
64:   ASan internal:           fe
64:   Left alloca redzone:     ca
64:   Right alloca redzone:    cb
64:   Shadow gap:              cc
64: ==3401==ABORTING
21/32 Test #64: c-benchmarks ..........................***Failed   56.04 sec
54: ::OpenPropertiesConfigTest::test_02_verify_connector_properties 
54: Router Router0 output file:
54: >>>>
```
https://github.com/skupperproject/skupper-router/runs/5667973245?check_suite_focus=true#step:9:2297

**Comment by jiridanek** [comment]
Duplicate of https://github.com/skupperproject/skupper-router/issues/225
