### ISSUE TITLE
system_tests_http1_over_tcp failing with asan: use-after-poison error

### ISSUE THREAD

**Issue by ganeshmurthy** [skupperproject/skupper-router#232]
```
58: E           Process 2412 error: exit code 1, expected 0
58: E           skrouterd -c INT.A.conf -I /home/runner/work/skupper-router/skupper-router/skupper-router/python
58: E           /__w/skupper-router/skupper-router/skupper-router/build/tests/system_test.dir/system_tests_http1_over_tcp/Http1OverTcpOneRouterTest/setUpClass/INT.A-4.cmd
58: E           >>>>
58: E           =================================================================
58: E           ==2412==ERROR: AddressSanitizer: use-after-poison on address 0x61300005d618 at pc 0x00000056ce28 bp 0x7f4dbdbe8180 sp 0x7f4dbdbe8178
58: E           WRITE of size 1 at 0x61300005d618 thread T1
58: E               #0 0x56ce27 in _plog_end_record_TH /home/runner/work/skupper-router/skupper-router/skupper-router/src/protocol_log.c:309
58: E               #1 0x56ce27 in _plog_end_record_TH /home/runner/work/skupper-router/skupper-router/skupper-router/src/protocol_log.c:298
58: E               #2 0x571b3a in _plog_thread /home/runner/work/skupper-router/skupper-router/skupper-router/src/protocol_log.c:960
58: E               #3 0x7f4dc3c51b19 in start_thread (/lib64/libc.so.6+0x8db19)
58: E               #4 0x7f4dc3cd665f in __GI___clone3 (/lib64/libc.so.6+0x11265f)
58: E           
58: E           0x61300005d618 is located 280 bytes inside of 320-byte region [0x61300005d500,0x61300005d640)
58: E           allocated by thread T3 here:
58: E               #0 0x7f4dc521a4fc in __interceptor_posix_memalign (/lib64/libasan.so.6+0xaf4fc)
58: E               #1 0x4beced in qd_alloc /home/runner/work/skupper-router/skupper-router/skupper-router/src/alloc_pool.c:396
58: E               #2 0x572810 in new_plog_record_t /home/runner/work/skupper-router/skupper-router/skupper-router/src/protocol_log.c:75
58: E               #3 0x572810 in plog_start_record /home/runner/work/skupper-router/skupper-router/skupper-router/src/protocol_log.c:1069
58: E               #4 0x4a1f4d in qdr_tcp_connection_egress /home/runner/work/skupper-router/skupper-router/skupper-router/src/adaptors/tcp_adaptor.c:1098
58: E               #5 0x4b41f9 in qdr_tcp_deliver /home/runner/work/skupper-router/skupper-router/skupper-router/src/adaptors/tcp_adaptor.c:1655
58: E               #6 0x622416 in qdr_link_process_deliveries /home/runner/work/skupper-router/skupper-router/skupper-router/src/router_core/transfer.c:194
58: E               #7 0x59a5e1 in qdr_connection_process /home/runner/work/skupper-router/skupper-router/skupper-router/src/router_core/connections.c:401
58: E               #8 0x4aa011 in on_activate /home/runner/work/skupper-router/skupper-router/skupper-router/src/adaptors/tcp_adaptor.c:200
58: E               #9 0x6833e6 in qd_timer_visit /home/runner/work/skupper-router/skupper-router/skupper-router/src/timer.c:320
58: E               #10 0x674076 in handle /home/runner/work/skupper-router/skupper-router/skupper-router/src/server.c:980
58: E               #11 0x67b975 in thread_run /home/runner/work/skupper-router/skupper-router/skupper-router/src/server.c:1095
58: E               #12 0x7f4dc3c51b19 in start_thread (/lib64/libc.so.6+0x8db19)
58: E           
58: E           Thread T1 created by T0 here:
58: E               #0 0x7f4dc51c1866 in pthread_create (/lib64/libasan.so.6+0x56866)
58: E               #1 0x560e65 in sys_thread /home/runner/work/skupper-router/skupper-router/skupper-router/src/posix/threading.c:181
58: E               #2 0x573baf in _plog_init /home/runner/work/skupper-router/skupper-router/skupper-router/src/protocol_log.c:1268
58: E               #3 0x60b76b in qdr_adaptors_init /home/runner/work/skupper-router/skupper-router/skupper-router/src/router_core/router_core_thread.c:165
58: E               #4 0x5f5686 in qdr_core_setup_init /home/runner/work/skupper-router/skupper-router/skupper-router/src/router_core/router_core.c:67
58: E               #5 0x5f5686 in qdr_core /home/runner/work/skupper-router/skupper-router/skupper-router/src/router_core/router_core.c:117
58: E               #6 0x6642e2 in qd_router_setup_late /home/runner/work/skupper-router/skupper-router/skupper-router/src/router_node.c:2083
58: E               #7 0x7f4dbf93dc03 in ffi_call_unix64 (/lib64/libffi.so.6+0x6c03)
58: E               #8 0x7fffab1cfe9f  ([stack]+0x1ee9f)
58: E           
58: E           Thread T3 created by T0 here:
58: E               #0 0x7f4dc51c1866 in pthread_create (/lib64/libasan.so.6+0x56866)
58: E               #1 0x560e65 in sys_thread /home/runner/work/skupper-router/skupper-router/skupper-router/src/posix/threading.c:181
58: E               #2 0x67deec in qd_server_run /home/runner/work/skupper-router/skupper-router/skupper-router/src/server.c:1489
58: E               #3 0x432fed in main_process /home/runner/work/skupper-router/skupper-router/skupper-router/router/src/main.c:105
58: E               #4 0x431ea2 in main /home/runner/work/skupper-router/skupper-router/skupper-router/router/src/main.c:359
58: E               #5 0x7f4dc3bf155f in __libc_start_call_main (/lib64/libc.so.6+0x2d55f)
58: E           
58: E           SUMMARY: AddressSanitizer: use-after-poison /home/runner/work/skupper-router/skupper-router/skupper-router/src/protocol_log.c:309 in _plog_end_record_TH
58: E           Shadow bytes around the buggy address:
58: E             0x0c2680003a70: 00 00 00 00 00 00 00 00 00 00 f7 f7 f7 f7 f7 f7
58: E             0x0c2680003a80: f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 00 00 00 00
58: E             0x0c2680003a90: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
58: E             0x0c2680003aa0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
58: E             0x0c2680003ab0: 00 00 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7
58: E           =>0x0c2680003ac0: f7 f7 f7[f7]00 00 00 00 fa fa fa fa fa fa fa fa
58: E             0x0c2680003ad0: fa fa fa fa fa fa fa fa 00 00 00 00 00 00 00 00
58: E             0x0c2680003ae0: 00 00 00 00 00 00 00 00 00 00 f7 f7 f7 f7 f7 f7
58: E             0x0c2680003af0: f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 f7 00 00 00 00
58: E             0x0c2680003b00: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
58: E             0x0c2680003b10: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
58: E           Shadow byte legend (one shadow byte represents 8 application bytes):
58: E             Addressable:           00
58: E             Partially addressable: 01 02 03 04 05 06 07 
58: E             Heap left redzone:       fa
58: E             Freed heap region:       fd
58: E             Stack left redzone:      f1
58: E             Stack mid redzone:       f2
58: E             Stack right redzone:     f3
58: E             Stack after return:      f5
58: E             Stack use after scope:   f8
58: E             Global redzone:          f9
58: E             Global init order:       f6
58: E             Poisoned by user:        f7
58: E             Container overflow:      fc
58: E             Array cookie:            ac
58: E             Intra object redzone:    bb
58: E             ASan internal:           fe
58: E             Left alloca redzone:     ca
58: E             Right alloca redzone:    cb
58: E             Shadow gap:              cc
58: E           ==2412==ABORTING
58: E           <<<<
```

https://github.com/skupperproject/skupper-router/runs/5667757081?check_suite_focus=true#step:26:2695

**Comment by jiridanek** [comment]
Duplicates https://github.com/skupperproject/skupper-router/issues/228

**Comment by ganeshmurthy** [comment]
Duplicate issue, closing
