### ISSUE TITLE
[Arm64] system_tests_router_mesh local-idle-timeout expired in test_06_parallel_priority (system_tests_router_mesh.ThreeRouterTest) 

### ISSUE THREAD

**Issue by jiridanek** [skupperproject/skupper-router#300]
https://app.travis-ci.com/github/jiridanek/skupper-router/jobs/566406796#L7323

```
53: ======================================================================
53: ERROR: test_06_parallel_priority (system_tests_router_mesh.ThreeRouterTest)
53: Create 10 senders each with a different priority.
53: ----------------------------------------------------------------------
53: Traceback (most recent call last):
53:   File "/home/travis/build/jiridanek/skupper-router/tests/system_tests_router_mesh.py", line 214, in test_06_parallel_priority
53:     self.RouterA.wait_address("closest/test_06_address")
53:   File "/home/travis/build/jiridanek/skupper-router/tests/system_test.py", line 675, in wait_address
53:     assert retry(check, **retry_kwargs)
53:   File "/home/travis/build/jiridanek/skupper-router/tests/system_test.py", line 138, in retry
53:     ret = function()
53:   File "/home/travis/build/jiridanek/skupper-router/tests/system_test.py", line 666, in check
53:     addrs = self.management.query(
53:   File "/home/travis/build/jiridanek/skupper-router/python/skupper_router/management/client.py", line 277, in query
53:     response = self.call(request)
53:   File "/home/travis/build/jiridanek/skupper-router/python/skupper_router/management/client.py", line 191, in call
53:     response = self.client.call(request)
53:   File "/home/travis/build/jiridanek/skupper-router/qpid-proton/python/proton/_utils.py", line 615, in call
53:     self.sender.send(request)
53:   File "/home/travis/build/jiridanek/skupper-router/qpid-proton/python/proton/_utils.py", line 140, in send
53:     self.connection.wait(lambda: _is_settled(delivery), msg="Sending on sender %s" % self.link.name,
53:   File "/home/travis/build/jiridanek/skupper-router/qpid-proton/python/proton/_utils.py", line 524, in wait
53:     self.container.process()
53:   File "/home/travis/build/jiridanek/skupper-router/qpid-proton/python/proton/_reactor.py", line 260, in process
53:     event.dispatch(handler)
53:   File "/home/travis/build/jiridanek/skupper-router/qpid-proton/python/proton/_events.py", line 158, in dispatch
53:     _dispatch(handler, type.method, self)
53:   File "/home/travis/build/jiridanek/skupper-router/qpid-proton/python/proton/_events.py", line 129, in _dispatch
53:     m(*args)
53:   File "/home/travis/build/jiridanek/skupper-router/qpid-proton/python/proton/_utils.py", line 552, in on_connection_remote_close
53:     raise ConnectionClosed(event.connection)
53: proton._utils.ConnectionClosed: Connection 0.0.0.0 closed due to: Condition('amqp:resource-limit-exceeded', 'local-idle-timeout expired')
53: 
53: ======================================================================
53: ERROR: test_06_parallel_priority (system_tests_router_mesh.ThreeRouterTest)
53: Create 10 senders each with a different priority.
53: ----------------------------------------------------------------------
53: Traceback (most recent call last):
53:   File "/home/travis/build/jiridanek/skupper-router/tests/system_test.py", line 929, in tearDown
53:     Tester.teardown(self)
53:   File "/home/travis/build/jiridanek/skupper-router/tests/system_test.py", line 870, in teardown
53:     raise RuntimeError("Errors during teardown: \n\n%s" % "\n\n".join([str(e) for e in errors]))
53: RuntimeError: Errors during teardown: 
53: 
53: Process 13563 error: still running
53: test-receiver -a 127.0.0.1:20439 -c 250 -s closest/test_06_address -d
53: /home/travis/build/jiridanek/skupper-router/build/tests/system_test.dir/system_tests_router_mesh/ThreeRouterTest/test_06_parallel_priority/test-receiver-43.cmd
53: >>>>
53: <<<<
53: 
53: ----------------------------------------------------------------------
53: Ran 6 tests in 168.918s
53: 
53: FAILED (errors=2)
56/66 Test #53: system_tests_router_mesh ................***Failed  169.05 sec
```

This is rather frequent failure on the Arm64 platform. Fails almost all the time on Travis CI.

**Comment by jiridanek** [comment]
https://app.travis-ci.com/github/jiridanek/skupper-router/jobs/578919831#L6888

**Comment by jiridanek** [comment]
Still present, https://app.travis-ci.com/github/jiridanek/skupper-router/jobs/597824514#L4682

**Comment by ganeshmurthy** [comment]
We don't see this failure in the recent arm runs. Closing
