### ISSUE TITLE
[s390x] system_tests_tcp_adaptor TcpAdaptorListenerConnectTest free(): invalid pointer

### ISSUE THREAD

**Issue by jiridanek** [skupperproject/skupper-router#304]
https://download.copr.fedorainfracloud.org/results/jdanek/skupper-router/epel-8-s390x/04119315-skupper-router/builder-live.log.gz

```
62/66 Test #62: system_tests_tcp_adaptor ................***Failed   39.90 sec
2022-04-08 16:52:56.959369 SERVER (info) Container Name: TCP_TEST
2022-04-08 16:52:56.959554 TCP_TEST Launching echo server 'ECHO_SERVER TcpAdaptor ES_INTA'
2022-04-08 16:52:56.959888 TCP_TEST Launching echo server 'ECHO_SERVER TcpAdaptor ES_INTB'
2022-04-08 16:52:56.960100 TCP_TEST Launching echo server 'ECHO_SERVER TcpAdaptor ES_INTC'
2022-04-08 16:52:56.960296 TCP_TEST Launching echo server 'ECHO_SERVER TcpAdaptor ES_EA1'
2022-04-08 16:52:56.960494 TCP_TEST Launching echo server 'ECHO_SERVER TcpAdaptor ES_EA2'
2022-04-08 16:52:56.960683 TCP_TEST Launching echo server 'ECHO_SERVER TcpAdaptor ES_EB1'
2022-04-08 16:52:56.960875 TCP_TEST Launching echo server 'ECHO_SERVER TcpAdaptor ES_EB2'

[...]

2022-04-08 16:53:14.171674 TCP_TEST Stopping echo server ES_EB2
2022-04-08 16:53:14.271828 TCP_TEST Stopping echo server ES_EC1
2022-04-08 16:53:14.371972 TCP_TEST Stopping echo server ES_EC2
2022-04-08 16:53:14.462446 TCP_TEST Stopping echo server NS_EC2_CONN_STALL
ok
test_01_no_service (system_tests_tcp_adaptor.TcpAdaptorListenerConnectTest) ... ok

Router TCPListenConnB output file:
>>>>
free(): invalid pointer

<<<<

Router TCPListenConnB output file:
>>>>
free(): invalid pointer

<<<<

Router TCPListenConnB command file:
>>>>
skrouterd -c TCPListenConnB.conf -I /builddir/build/BUILD/skupper-router/python
pid=4245

<<<<

Router TCPListenConnB log file tail:
>>>>
2022-04-08 16:53:18.840935 +0000 PROTOCOL (trace) [C2]:FRAME: 0 -> @transfer(20) [handle=0x1, delivery-id=0x9, delivery-tag=b"\x00\x00\x00\x00\x00\x00\x00\x0b", message-format=0x0, settled=true] (238) \x00\x80SKPR--RA\xd0\x00\x00\x003\x00\x00\x00\x04C@\xa1\x100/TCPListenConnB\xd0\x00\x00\x00\x16\x00\x00\x00\x01\xa1\x100/TCPListenConnB\x00Sp\xd0\x00\x00\x00\x05\x00\x00\x00\x01B\x00Ss\xd0\x00\x00\x00\x1f\x00\x00\x00\x06@@\xa1\x14amqp:/_local/qdhello@@@\x00St\xd1\x00\x00\x00\x13\x00\x00\x00\x02\xa1\x06opcode\xa1\x05HELLO\x00Sw\xd1\x00\x00\x00U\x00\x00\x00\x0a\xa1\x02id\xa1\x0eTCPListenConnB\xa1\x02pvT\x01\xa1\x04area\xa1\x010\xa1\x08instanceqbPhz\xa1\x04seen\xd0\x00\x00\x00\x14\x00\x00\x00\x01\xa1\x0eTCPLi ... (truncated) (/builddir/build/BUILD/skupper-router/src/server.c:110)
2022-04-08 16:53:18.840951 +0000 ROUTER_CORE (trace) Core action 'process_tick' (/builddir/build/BUILD/skupper-router/src/router_core/router_core_thread.c:246)
2022-04-08 16:53:18.840956 +0000 ROUTER_CORE (trace) Core action 'link_flow' (/builddir/build/BUILD/skupper-router/src/router_core/router_core_thread.c:246)
2022-04-08 16:53:18.841252 +0000 PROTOCOL (trace) [C2]:FRAME: 0 <- @flow(19) [next-incoming-id=0xa, incoming-window=0x7fffffff, next-outgoing-id=0xa, outgoing-window=0x7fffffff, handle=0x1, delivery-count=0xa, link-credit=0xfa, drain=false] (/builddir/build/BUILD/skupper-router/src/server.c:110)
2022-04-08 16:53:18.841269 +0000 ROUTER_CORE (trace) Core action 'link_flow' (/builddir/build/BUILD/skupper-router/src/router_core/router_core_thread.c:246)
2022-04-08 16:53:18.972978 +0000 PROTOCOL (trace) [C4]:FRAME: 0 <- @flow(19) [next-incoming-id=0x1, incoming-window=0x7fffffff, next-outgoing-id=0x1, outgoing-window=0x7fffffff, handle=0x1, delivery-count=0x1, link-credit=0x1, drain=false] (/builddir/build/BUILD/skupper-router/src/server.c:110)
2022-04-08 16:53:18.972993 +0000 PROTOCOL (trace) [C4]:FRAME: 0 <- @close(24) [] (/builddir/build/BUILD/skupper-router/src/server.c:110)
2022-04-08 16:53:18.973000 +0000 PROTOCOL (trace) [C4]:FRAME:   <- EOS (/builddir/build/BUILD/skupper-router/src/server.c:110)
2022-04-08 16:53:18.973021 +0000 PROTOCOL (trace) [C4]:FRAME: 0 -> @close(24) [] (/builddir/build/BUILD/skupper-router/src/server.c:110)
2022-04-08 16:53:18.973036 +0000 PROTOCOL (trace) [C4]:FRAME:   -> EOS (/builddir/build/BUILD/skupper-router/src/server.c:110)
2022-04-08 16:53:18.973093 +0000 ROUTER_CORE (trace) Core action 'link_flow' (/builddir/build/BUILD/skupper-router/src/router_core/router_core_thread.c:246)
2022-04-08 16:53:18.973098 +0000 ROUTER_CORE (trace) Core action 'link_detach' (/builddir/build/BUILD/skupper-router/src/router_core/router_core_thread.c:246)
2022-04-08 16:53:18.973108 +0000 ROUTER_CORE (info) [C4][L26] Link lost: del=1 presett=0 psdrop=0 acc=1 rej=0 rel=0 mod=0 delay1=0 delay10=0 blocked=no (/builddir/build/BUILD/skupper-router/src/router_core/connections.c:1101)
2022-04-08 16:53:18.973113 +0000 ROUTER_CORE (trace) Core action 'link_detach' (/builddir/build/BUILD/skupper-router/src/router_core/router_core_thread.c:246)
2022-04-08 16:53:18.973118 +0000 ROUTER_CORE (info) [C4][L27] Link lost: del=1 presett=1 psdrop=0 acc=0 rej=0 rel=0 mod=0 delay1=0 delay10=0 blocked=no (/builddir/build/BUILD/skupper-router/src/router_core/connections.c:1101)
2022-04-08 16:53:18.973124 +0000 ROUTER_CORE (trace) Core action 'connection_closed' (/builddir/build/BUILD/skupper-router/src/router_core/router_core_thread.c:246)
2022-04-08 16:53:18.973128 +0000 ROUTER_CORE (info) [C4] Connection Closed (/builddir/build/BUILD/skupper-router/src/router_core/connections.c:1568)
2022-04-08 16:53:18.973780 +0000 SERVER (notice) Shut Down (/builddir/build/BUILD/skupper-router/src/server.c:1498)
2022-04-08 16:53:18.973792 +0000 HTTP (trace) lws_context_destroy: ctx 0x2aa37002850 (/builddir/build/BUILD/skupper-router/src/http-libwebsockets.c:62)
2022-04-08 16:53:18.973800 +0000 HTTP (trace) _lws_state_transition: system: changed 1 'CONTEXT_CREATED' -> 11 'POLICY_INVALID' (/builddir/build/BUILD/skupper-router/src/http-libwebsockets.c:62)
2022-04-08 16:53:18.973804 +0000 HTTP (trace) lws_destroy_event_pipe (/builddir/build/BUILD/skupper-router/src/http-libwebsockets.c:62)
2022-04-08 16:53:18.973813 +0000 HTTP (trace) lws_pt_destroy: pt destroyed (/builddir/build/BUILD/skupper-router/src/http-libwebsockets.c:62)
2022-04-08 16:53:18.973816 +0000 HTTP (trace) lws_context_destroy2: ctx 0x2aa37002850 (/builddir/build/BUILD/skupper-router/src/http-libwebsockets.c:62)
2022-04-08 16:53:18.973833 +0000 HTTP (trace) 0x3ff7f25fc1a: post vh listl (/builddir/build/BUILD/skupper-router/src/http-libwebsockets.c:62)
2022-04-08 16:53:18.973837 +0000 HTTP (trace) 0x3ff7f25fc1a: post pdl (/builddir/build/BUILD/skupper-router/src/http-libwebsockets.c:62)
2022-04-08 16:53:18.973848 +0000 HTTP (trace) 0x3ff7f25fc1a: baggage (/builddir/build/BUILD/skupper-router/src/http-libwebsockets.c:62)
2022-04-08 16:53:18.973852 +0000 HTTP (trace) 0x3ff7f25fc1a: post dc2 (/builddir/build/BUILD/skupper-router/src/http-libwebsockets.c:62)
2022-04-08 16:53:18.973855 +0000 HTTP (trace) lws_context_destroy3 (/builddir/build/BUILD/skupper-router/src/http-libwebsockets.c:62)
2022-04-08 16:53:18.973866 +0000 HTTP (trace) lws_system_blob_destroy: blob 0x2aa37002970 (/builddir/build/BUILD/skupper-router/src/http-libwebsockets.c:62)
2022-04-08 16:53:18.973870 +0000 HTTP (trace) lws_system_blob_destroy: blob 0x2aa37002988 (/builddir/build/BUILD/skupper-router/src/http-libwebsockets.c:62)
2022-04-08 16:53:18.973873 +0000 HTTP (trace) lws_system_blob_destroy: blob 0x2aa370029a0 (/builddir/build/BUILD/skupper-router/src/http-libwebsockets.c:62)
2022-04-08 16:53:18.973877 +0000 HTTP (trace) lws_system_blob_destroy: blob 0x2aa370029b8 (/builddir/build/BUILD/skupper-router/src/http-libwebsockets.c:62)
2022-04-08 16:53:18.973880 +0000 HTTP (trace) lws_system_blob_destroy: blob 0x2aa370029d0 (/builddir/build/BUILD/skupper-router/src/http-libwebsockets.c:62)
2022-04-08 16:53:18.973883 +0000 HTTP (trace) lws_system_blob_destroy: blob 0x2aa370029e8 (/builddir/build/BUILD/skupper-router/src/http-libwebsockets.c:62)
2022-04-08 16:53:18.973887 +0000 HTTP (trace) lws_system_blob_destroy: blob 0x2aa37002a00 (/builddir/build/BUILD/skupper-router/src/http-libwebsockets.c:62)
2022-04-08 16:53:18.973890 +0000 HTTP (trace) lws_system_blob_destroy: blob 0x2aa37002a18 (/builddir/build/BUILD/skupper-router/src/http-libwebsockets.c:62)
2022-04-08 16:53:18.973894 +0000 HTTP (trace) lws_context_destroy3: ctx 0x2aa37002850 freed (/builddir/build/BUILD/skupper-router/src/http-libwebsockets.c:62)
2022-04-08 16:53:18.973920 +0000 CONTAINER (trace) Default node removed (/builddir/build/BUILD/skupper-router/src/container.c:849)
2022-04-08 16:53:18.973929 +0000 ROUTER_CORE (info) Router Core thread exited (/builddir/build/BUILD/skupper-router/src/router_core/router_core_thread.c:267)
2022-04-08 16:53:18.973948 +0000 HTTP_ADAPTOR (trace) Shutting down HTTP2 Protocol adaptor (/builddir/build/BUILD/skupper-router/src/adaptors/http2/http2_adaptor.c:2709)
2022-04-08 16:53:18.973958 +0000 TCP_ADAPTOR (info) Shutting down TCP protocol adaptor (/builddir/build/BUILD/skupper-router/src/adaptors/tcp_adaptor.c:1908)
2022-04-08 16:53:18.973963 +0000 TCP_ADAPTOR (info) Deleted TCP bridge configuation 'tcpConnector/127.0.0.1:23210' for address TCPListenConnTest/service, 127.0.0.1:23210, siteId (null). Connections opened:2, closed:2. Bytes in:0, out:0 (/builddir/build/BUILD/skupper-router/src/adaptors/tcp_adaptor.c:1173)
2022-04-08 16:53:18.973979 +0000 FLOW_LOG (info) Protocol logging completed (/builddir/build/BUILD/skupper-router/src/protocol_log.c:1047)
2022-04-08 16:53:18.974217 +0000 ROUTER_CORE (info) Finalizing core module: streaming_link_scrubber (/builddir/build/BUILD/skupper-router/src/router_core/router_core_thread.c:149)
2022-04-08 16:53:18.974222 +0000 ROUTER_CORE (info) Finalizing core module: mobile_sync (/builddir/build/BUILD/skupper-router/src/router_core/router_core_thread.c:149)
2022-04-08 16:53:18.974227 +0000 ROUTER_CORE (info) Finalizing core module: stuck_delivery_detection (/builddir/build/BUILD/skupper-router/src/router_core/router_core_thread.c:149)
2022-04-08 16:53:18.974231 +0000 ROUTER_CORE (info) Finalizing core module: heartbeat_server (/builddir/build/BUILD/skupper-router/src/router_core/router_core_thread.c:149)
2022-04-08 16:53:18.974235 +0000 ROUTER_CORE (info) Finalizing core module: address_lookup_client (/builddir/build/BUILD/skupper-router/src/router_core/router_core_thread.c:149)
2022-04-08 16:53:18.974238 +0000 ROUTER_CORE (info) Finalizing core module: edge_addr_tracking (/builddir/build/BUILD/skupper-router/src/router_core/router_core_thread.c:149)
2022-04-08 16:53:18.974278 +0000 SERVER (info) [C2] Closing connection on shutdown (/builddir/build/BUILD/skupper-router/src/server.c:1378)

<<<<
ERROR
test_01_mgmt (system_tests_tcp_adaptor.TcpAdaptorManagementTest) ... ok
test_01_ignore_stuck_deliveries (system_tests_tcp_adaptor.TcpAdaptorStuckDeliveryTest) ... ok

======================================================================
ERROR: tearDownClass (system_tests_tcp_adaptor.TcpAdaptorListenerConnectTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/skupper-router/tests/system_test.py", line 920, in tearDownClass
    cls.tester.teardown()
  File "/builddir/build/BUILD/skupper-router/tests/system_test.py", line 870, in teardown
    raise RuntimeError("Errors during teardown: \n\n%s" % "\n\n".join([str(e) for e in errors]))
RuntimeError: Errors during teardown: 

Process 4245 error: exit code -6, expected 0
skrouterd -c TCPListenConnB.conf -I /builddir/build/BUILD/skupper-router/python
/builddir/build/BUILD/skupper-router/s390x-redhat-linux-gnu/tests/system_test.dir/system_tests_tcp_adaptor/TcpAdaptorListenerConnectTest/setUpClass/TCPListenConnB-11.cmd
>>>>
free(): invalid pointer
<<<<

----------------------------------------------------------------------
Ran 13 tests in 39.779s

FAILED (errors=1, skipped=2)
```

**Comment by jiridanek** [comment]
Probably the same problem on x86_64 https://download.copr.fedorainfracloud.org/results/jdanek/skupper-router/fedora-rawhide-x86_64/04119315-skupper-router/builder-live.log.gz

**Comment by jiridanek** [comment]
```
Thread 4 "skrouterd" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff545e500 (LWP 8308)]
qdr_tcp_connection_egress (connector=<optimized out>, config=<optimized out>, server=<optimized out>, initial_delivery=initial_delivery@entry=0x1005644c8) at /builddir/build/BUILD/skupper-router/src/adaptors/tcp_adaptor.c:1143
1143	        if (pn_netaddr_host_port(na, local_host, 200, local_port, 50) == 0) {
```

So this appears to be a duplicate of https://github.com/skupperproject/skupper-router/issues/230#issuecomment-1088644269
