### ISSUE TITLE
Runtime error: null pointer passed as argument 1, which is declared to never be null

### ISSUE THREAD

**Issue by ganeshmurthy** [skupperproject/skupper-router#316]
```
 9: ../../src/protocol_log.c:1328:25: runtime error: null pointer passed as argument 1, which is declared to never be null
63: ../../src/protocol_log.c:1328:25: runtime error: null pointer passed as argument 1, which is declared to never be null
```
https://github.com/jiridanek/skupper-router/runs/5975988010?check_suite_focus=true#step:9:227

**Comment by jiridanek** [comment]
The rest of the backtrace seems to be a little bit bellow. The output from tests 9: and 63:, showing stacktraces for the same thing, is interleaved in it. Funny.

```
9:     #0 0x5617c86340e9 in _plog_init ../../src/protocol_log.c:1328
9:     #1 0x5617c86e4760 in qdr_adaptors_init ../../src/router_core/router_core_thread.c:165
9:     #2 0x5617c86c539f in qdr_core_setup_init ../../src/router_core/router_core.c:67
9:     #3 0x5617c86c61f7 in qdr_core ../../src/router_core/router_core.c:117
9:     #4 0x5617c87544a0 in qd_router_setup_late ../../src/router_node.c:2058
9:     #5 0x7fa7c5155ff4  (/lib/x86_64-linux-gnu/libffi.so.7+0x6ff4)
9:     #6 0x7fa7c5155409  (/lib/x86_64-linux-gnu/libffi.so.7+0x6409)
63:     #0 0x55630159840b in _plog_init ../../src/protocol_log.c:1328
63:     #1 0x556301648a82 in qdr_adaptors_init ../../src/router_core/router_core_thread.c:165
63:     #2 0x5563016[296](https://github.com/jiridanek/skupper-router/runs/5975988010?check_suite_focus=true#step:9:296)c1 in qdr_core_setup_init ../../src/router_core/router_core.c:67
63:     #3 0x55630162a519 in qdr_core ../../src/router_core/router_core.c:117
63:     #4 0x5563016b87c2 in qd_router_setup_late ../../src/router_node.c:2058
63:     #5 0x7f4e5f508ff4  (/lib/x86_64-linux-gnu/libffi.so.7+0x6ff4)
63:     #6 0x7f4e5f508409  (/lib/x86_64-linux-gnu/libffi.so.7+0x6409)
9:     #7 0x7fa7c516d912 in _call_function_pointer /home/vsts/work/1/s/SourceCode/Modules/_ctypes/callproc.c:818
63:     #7 0x7f4e5f226912 in _call_function_pointer /home/vsts/work/1/s/SourceCode/Modules/_ctypes/callproc.c:818
63:     #8 0x7f4e5f226912 in _ctypes_callproc /home/vsts/work/1/s/SourceCode/Modules/_ctypes/callproc.c:1182
9:     #8 0x7fa7c516d912 in _ctypes_callproc /home/vsts/work/1/s/SourceCode/Modules/_ctypes/callproc.c:1182
9:     #9 0x7fa7c51697a3 in PyCFuncPtr_call /home/vsts/work/1/s/SourceCode/Modules/_ctypes/_ctypes.c:3970
63:     #9 0x7f4e5f2227a3 in PyCFuncPtr_call /home/vsts/work/1/s/SourceCode/Modules/_ctypes/_ctypes.c:3970
```
