### ISSUE TITLE
system_tests_tcp_adaptor AddressSanitizer: use-after-poison in `plog_latency_start`

### ISSUE THREAD

**Issue by jiridanek** [skupperproject/skupper-router#317]
https://github.com/jiridanek/skupper-router/runs/5976545736?check_suite_focus=true#step:26:3560

```
58: ==2712==ERROR: AddressSanitizer: use-after-poison on address 0x61300008d498 at pc 0x000000579789 bp 0x7f242c116800 sp 0x7f242c1167f8
58: WRITE of size 8 at 0x61300008d498 thread T4
58:     #0 0x579788 in plog_latency_start /home/runner/work/skupper-router/skupper-router/skupper-router/src/
58:     #1 0x4a2e96 in qdr_tcp_connection_egress /home/runner/work/skupper-router/skupper-router/skupper-router/src/adaptors/tcp_adaptor.c:1138
58:     #2 0x4b52f1 in qdr_tcp_deliver /home/runner/work/skupper-router/skupper-router/skupper-router/src/adaptors/tcp_adaptor.c:1671
58:     #3 0x6284c6 in qdr_link_process_deliveries /home/runner/work/skupper-router/skupper-router/skupper-router/src/router_core/transfer.c:180
58:     #4 0x59f8a1 in qdr_connection_process /home/runner/work/skupper-router/skupper-router/skupper-router/src/router_core/connections.c:407
58:     #5 0x4ab731 in on_activate /home/runner/work/skupper-router/skupper-router/skupper-router/src/adaptors/tcp_adaptor.c:201
58:     #6 0x689216 in qd_timer_visit /home/runner/work/skupper-router/skupper-router/skupper-router/src/timer.c:320
58:     #7 0x679ea6 in handle /home/runner/work/skupper-router/skupper-router/skupper-router/src/server.c:980
58:     #8 0x6817a5 in thread_run /home/runner/work/skupper-router/skupper-router/skupper-router/src/server.c:1095
58:     #9 0x7f24373e6b19 in start_thread (/lib64/libc.so.6+0x8db19)
58:     #10 0x7f243746b65f in __GI___clone3 (/lib64/libc.so.6+0x11265f)
58: 
58: 0x61300008d498 is located 280 bytes inside of 320-byte region [0x61300008d380,0x61300008d4c0)
58: allocated by thread T4 here:
58:     #0 0x7f24389be4fc in __interceptor_posix_memalign (/lib64/libasan.so.6+0xaf4fc)
58:     #1 0x4bfc7d in qd_alloc /home/runner/work/skupper-router/skupper-router/skupper-router/src/alloc_pool.c:396
58:     #2 0x57673c in new_plog_record_t /home/runner/work/skupper-router/skupper-router/skupper-router/src/protocol_log.c:81
58:     #3 0x57673c in plog_start_record /home/runner/work/skupper-router/skupper-router/skupper-router/src/protocol_log.c:1136
58:     #4 0x4a2fbc in qdr_tcp_connection_egress /home/runner/work/skupper-router/skupper-router/skupper-router/src/adaptors/tcp_adaptor.c:1113
58:     #5 0x4b52f1 in qdr_tcp_deliver /home/runner/work/skupper-router/skupper-router/skupper-router/src/adaptors/tcp_adaptor.c:1671
58:     #6 0x6284c6 in qdr_link_process_deliveries /home/runner/work/skupper-router/skupper-router/skupper-router/src/router_core/transfer.c:180
58:     #7 0x59f8a1 in qdr_connection_process /home/runner/work/skupper-router/skupper-router/skupper-router/src/router_core/connections.c:407
58:     #8 0x4ab731 in on_activate /home/runner/work/skupper-router/skupper-router/skupper-router/src/adaptors/tcp_adaptor.c:201
58:     #9 0x689216 in qd_timer_visit /home/runner/work/skupper-router/skupper-router/skupper-router/src/timer.c:320
58:     #10 0x679ea6 in handle /home/runner/work/skupper-router/skupper-router/skupper-router/src/server.c:980
58:     #11 0x6817a5 in thread_run /home/runner/work/skupper-router/skupper-router/skupper-router/src/server.c:1095
58:     #12 0x7f24373e6b19 in start_thread (/lib64/libc.so.6+0x8db19)
58: 
58: Thread T4 created by T0 here:
58:     #0 0x7f2438965866 in pthread_create (/lib64/libasan.so.6+0x56866)
58:     #1 0x564465 in sys_thread /home/runner/work/skupper-router/skupper-router/skupper-router/src/posix/threading.c:181
58:     #2 0x683d1c in qd_server_run /home/runner/work/skupper-router/skupper-router/skupper-router/src/server.c:1489
58:     #3 0x43325d in main_process /home/runner/work/skupper-router/skupper-router/skupper-router/router/src/main.c:105
58:     #4 0x432112 in main /home/runner/work/skupper-router/skupper-router/skupper-router/router/src/main.c:359
58:     #5 0x7f243738655f in __libc_start_call_main (/lib64/libc.so.6+0x2d55f)
```

**Comment by ganeshmurthy** [comment]
This has been fixed by https://github.com/skupperproject/skupper-router/pull/291
