### ISSUE TITLE
`pn_record` leaks when running h2spec test

### ISSUE THREAD

**Issue by jiridanek** [skupperproject/skupper-router#386]
https://github.com/skupperproject/skupper-router/runs/6211445162?check_suite_focus=true#step:6:3785

related to https://github.com/skupperproject/skupper-router/issues/371

```
skrouterd: alloc.c: Items of type 'qd_buffer_t' remain allocated at shutdown: 220 (SUPPRESSED)
skrouterd: alloc.c: Items of type 'qd_message_t' remain allocated at shutdown: 73 (SUPPRESSED)
skrouterd: alloc.c: Items of type 'qd_message_content_t' remain allocated at shutdown: 73 (SUPPRESSED)
skrouterd: alloc.c: Items of type 'qdr_delivery_t' remain allocated at shutdown: 73 (SUPPRESSED)
skrouterd: 
skrouterd: =================================================================
skrouterd: ==1==ERROR: LeakSanitizer: detected memory leaks
skrouterd: 
skrouterd: Indirect leak of 96 byte(s) in 4 object(s) allocated from:
skrouterd:     #0 0x7fd225c8cfe8 in __interceptor_realloc (/lib64/libasan.so.5+0xeffe8)
skrouterd:     #1 0x57e000 in pn_record_def (/usr/sbin/skrouterd_asan+0x57e000) /build/qpid-proton-src/c/src/core/memory.c:275
skrouterd:     #2 0x5990b9 in pn_record (/usr/sbin/skrouterd_asan+0x5990b9) /build/qpid-proton-src/c/src/core/object/record.c:67
skrouterd:     #3 0x525197 in pn_event_initialize_cast (/usr/sbin/skrouterd_asan+0x525197) /build/qpid-proton-src/c/src/core/event.c:220
skrouterd:     #4 0x598c28 in pn_class_new (/usr/sbin/skrouterd_asan+0x598c28)
skrouterd:     #5 0x52f932 in pn_collector_put (/usr/sbin/skrouterd_asan+0x52f932)
skrouterd:     #6 0x58f419 in pni_raw_batch_next.lto_priv.658 (/usr/sbin/skrouterd_asan+0x58f419)
skrouterd:     #7 0x633dc6 in thread_run.lto_priv.634 (/usr/sbin/skrouterd_asan+0x633dc6)
skrouterd:     #8 0x7fd224fea179 in start_thread (/lib64/libpthread.so.0+0x8179)
skrouterd: 
skrouterd: Indirect leak of 24 byte(s) in 1 object(s) allocated from:
skrouterd:     #0 0x7fd225c8cfe8 in __interceptor_realloc (/lib64/libasan.so.5+0xeffe8)
skrouterd:     #1 0x57e000 in pn_record_def (/usr/sbin/skrouterd_asan+0x57e000)
skrouterd:     #2 0x5990b9 in pn_record (/usr/sbin/skrouterd_asan+0x5990b9)
skrouterd:     #3 0x525197 in pn_event_initialize_cast (/usr/sbin/skrouterd_asan+0x525197)
skrouterd:     #4 0x598c28 in pn_class_new (/usr/sbin/skrouterd_asan+0x598c28)
skrouterd:     #5 0x52f932 in pn_collector_put (/usr/sbin/skrouterd_asan+0x52f932)
skrouterd:     #6 0x5a4517 in praw_connection_connected_lh.lto_priv.749 (/usr/sbin/skrouterd_asan+0x5a4517)
skrouterd:     #7 0x63379a in thread_run.lto_priv.634 (/usr/sbin/skrouterd_asan+0x63379a)
skrouterd:     #8 0x7fd224fea179 in start_thread (/lib64/libpthread.so.0+0x8179)
skrouterd: 
skrouterd: -----------------------------------------------------
skrouterd: Suppressions used:
skrouterd:   count      bytes template
skrouterd:       1         56 ^IoAdapter_init$
skrouterd:      20       8560 ^pn_raw_connection$
skrouterd:     146       9344 sys_mutex
skrouterd:       8        488 ^pn_string_grow$
skrouterd:      33       1560 ^pn_object_new$
skrouterd:     631     869790 /libpython3.*.so
skrouterd: -----------------------------------------------------
skrouterd: 
skrouterd: SUMMARY: AddressSanitizer: 120 byte(s) leaked in 5 allocation(s).
```

**Comment by kgiusti** [comment]
@astitcher could this be a proton bug?
