### ISSUE TITLE
test_head_request failed in system_tests_http2_tls in flaky manner `AssertionError: False is not true`

### ISSUE THREAD

**Issue by jiridanek** [skupperproject/skupper-router#417]
https://app.travis-ci.com/github/jiridanek/skupper-router/jobs/568809767#L6092

This is Travis CI ppc64le, but I saw it on GitHub Actions as well. (On my PRs where it was not 100% certain that the PR did not broke things.) When I see it again, i'll add link to GHA because that has downloadable logs.

```
60: ======================================================================
60: FAIL: test_head_request (system_tests_http2_tls.Http2TlsAuthenticatePeerOneRouter)
60: ----------------------------------------------------------------------
60: Traceback (most recent call last):
60:   File "/home/travis/build/jiridanek/skupper-router/tests/system_tests_http2_tls.py", line 568, in test_head_request
60:     self.assertTrue(conn_closed)
60: AssertionError: False is not true
60: 
60: ----------------------------------------------------------------------
60: Ran 65 tests in 112.799s
60: 
60: FAILED (failures=1, skipped=5)
60/67 Test #60: system_tests_http2_tls ..................***Failed  131.98 sec
```

**Comment by jiridanek** [comment]
Ask, and Travis shall provideth, https://app.travis-ci.com/github/jiridanek/skupper-router/jobs/568978643#L10065

```
60: ======================================================================
60: FAIL: test_head_request (system_tests_http2_tls.Http2TlsAuthenticatePeerOneRouter)
60: ----------------------------------------------------------------------
60: Traceback (most recent call last):
60:   File "/home/travis/build/jiridanek/skupper-router/tests/system_tests_http2_tls.py", line 567, in test_head_request
60:     self.assertTrue(conn_closed, msg="err is %s and out is %s" % (err, out))
60: AssertionError: False is not true : err is curl: (52) Empty reply from server
60: 
60:  and out is 
60: 
60: ----------------------------------------------------------------------
60: Ran 65 tests in 161.666s
60: 
60: FAILED (failures=1, skipped=5)
60/67 Test #60: system_tests_http2_tls ..................***Failed  189.59 sec
```

**Comment by ganeshmurthy** [comment]
Yikes. When run on the ppc64le CPU architecture, the err is `curl: (52) Empty reply from server`
That is not what I expected. Does this test fail *every time* it is run under that particular architecture on Travis ?

**Comment by jiridanek** [comment]
No idea, let me push empty commit (or two), we will see:

* https://app.travis-ci.com/github/jiridanek/skupper-router/builds/250180061
* https://app.travis-ci.com/github/jiridanek/skupper-router/builds/250180082

**Comment by jiridanek** [comment]
Btw, one of the h2spec issues (https://github.com/skupperproject/skupper-router/issues/371) is about HEAD request timeouting. Maybe it is the same or in some way a similar problem (that can be addressed in a minor version some time in the future, instead of now).

**Comment by jiridanek** [comment]
Appears to be flaky on ppc64le. It fails often, but not always. It failed in both the two runs above, but when running on unrelated PR, there it passed. Also it is flaky on z390x there on Travis.

https://app.travis-ci.com/github/jiridanek/skupper-router/jobs/569003224#L6242

```
60: ======================================================================
60: FAIL: test_head_request (system_tests_http2_tls.Http2TlsAuthenticatePeerOneRouter)
60: ----------------------------------------------------------------------
60: Traceback (most recent call last):
60:   File "/home/travis/build/jiridanek/skupper-router/tests/system_tests_http2_tls.py", line 567, in test_head_request
60:     self.assertTrue(conn_closed, msg="err is %s and out is %s" % (err, out))
60: AssertionError: False is not true : err is #=#=#                                                                         
60: curl: (16) OpenSSL SSL_write: Broken pipe, errno 32
60: 
60:  and out is 
60: 
60: ----------------------------------------------------------------------
60: Ran 65 tests in 202.457s
60: 
60: FAILED (failures=1, skipped=5)
59/67 Test #60: system_tests_http2_tls ..................***Failed  226.16 sec
```

**Comment by jiridanek** [comment]
https://github.com/jiridanek/skupper-router/runs/6411836522?check_suite_focus=true#step:26:3056

```
56: >       self.assertTrue(conn_closed, msg="err is %s and out is %s" % (err, out))
56: E       AssertionError: False is not true : err is   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
56: E                                        Dload  Upload   Total   Spent    Left  Speed
56: E       
56: E         0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
56: E         0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
56: E         0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
56: E       curl: (16) OpenSSL SSL_write: Broken pipe, errno 32
56: E        and out is
56: 
56: /home/runner/work/skupper-router/skupper-router/skupper-router/tests/system_tests_http2_tls.py:567: AssertionError
```

**Comment by ganeshmurthy** [comment]
@cliffjansen is working on a fix that would send back to the client the exact reason why the TLS handshake failed. Once that lands, I will modify the http2 adaptor code and the test so it does not fail with these random error messages.

**Comment by jiridanek** [comment]
https://github.com/jiridanek/skupper-router/runs/6639403878?check_suite_focus=true#step:8:3505

Here it's somewhat more verbose. This is Ubuntu 22.04 with OpenSSL 3.0

```
56: >       self.assertTrue(conn_closed, msg="err is %s and out is %s" % (err, out))
56: E       AssertionError: False is not true : err is   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
56: E                                        Dload  Upload   Total   Spent    Left  Speed
56: E       
56: E         0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
56: E         0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
56: E       curl: (56) OpenSSL SSL_read: error:0A000126:SSL routines::unexpected eof while reading, errno 0
56: E        and out is
```

**Comment by jiridanek** [comment]
```
======================================================================
FAIL: test_connector_requires_client_auth_fail (system_tests_tcp_adaptor_tls.TcpAdaptorOpenSSLTests.test_connector_requires_client_auth_fail)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/skupper-router-2.1.0/tests/system_tests_tcp_adaptor_tls.py", line 450, in test_connector_requires_client_auth_fail
    _, _ = self.opensslclient(port=self.router_listener_port_server_auth_peer,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/builddir/build/BUILD/skupper-router-2.1.0/tests/system_test.py", line 1273, in opensslclient
    assert p.returncode == 0, \
           ^^^^^^^^^^^^^^^^^
AssertionError: openssl s_client failed with returncode 1 b'depth=1 CN = Trusted.CA.com, O = Trust Me Inc.\nverify return:1\ndepth=0 CN = localhost, O = Server\nverify return:1\n008E2936487F0000:error:0A000126:SSL routines:ssl3_read_n:unexpected eof while reading:ssl/record/rec_layer_s3.c:303:\n'
```

https://download.copr.fedorainfracloud.org/results/packit/skupperproject-skupper-router-1140/fedora-37-x86_64/06108931-skupper-router/builder-live.log.gz

**Comment by ganeshmurthy** [comment]
Closing this, will reopen if we see this again
