### ISSUE TITLE
system_tests_http1_adaptor, threading.c:58: sys_mutex_lock: Assertion `result == 0' failed.

### ISSUE THREAD

**Issue by jiridanek** [skupperproject/skupper-router#494]
This happened when running the router under rr. Somehow during shutdown, taking the `conn->work_lock` failed.

I have two rr recordings for this, so I'll try to investigate these more
- /home/jdanek/.local/share/rr/skrouterd-70
- /home/jdanek/.local/share/rr/skrouterd-294

[EA1.log.txt](https://github.com/skupperproject/skupper-router/files/8766235/EA1.log.txt)

```
#5  0x00007f52f1be35b6 in __GI___assert_fail (assertion=assertion@entry=0x4981a3 "result == 0", file=file@entry=0x498160 "/home/jdanek/repos/skupper-router/src/posix/threading.c", line=line@entry=58, 
    function=function@entry=0x4982a8 <__PRETTY_FUNCTION__.10> "sys_mutex_lock") at assert.c:101
#6  0x0000000000455ed1 in sys_mutex_lock (mutex=<optimized out>) at /home/jdanek/repos/skupper-router/src/posix/threading.c:58
#7  0x00000000004621c4 in qdr_link_enqueue_work_CT (core=0xbb2b60, link=0x7f52d4048d08, work=0x7f52d4122708) at /home/jdanek/repos/skupper-router/src/router_core/connections.c:756
#8  0x00000000004650bb in qdrc_event_addr_raise (core=core@entry=0xbb2b60, event=event@entry=33554432, addr=0x7f52d4016dc8) at /home/jdanek/repos/skupper-router/src/router_core/core_events.c:125
#9  0x000000000045bcc7 in qdr_address_watch_free_CT (watch=0x7f52d4023c88, core=0xbb2b60) at /home/jdanek/repos/skupper-router/src/router_core/address_watch.c:111
#10 qdr_address_watch_shutdown (core=core@entry=0xbb2b60) at /home/jdanek/repos/skupper-router/src/router_core/address_watch.c:99
#11 0x000000000046e510 in qdr_core_free (core=0xbb2b60) at /home/jdanek/repos/skupper-router/src/router_core/router_core.c:171
#12 0x000000000047e143 in qd_router_free (router=0xa5ef70) at /home/jdanek/repos/skupper-router/src/router_node.c:2096
#13 0x0000000000445fdd in qd_dispatch_free (qd=0x979d70) at /home/jdanek/repos/skupper-router/src/dispatch.c:356
#14 qd_dispatch_free (qd=0x979d70) at /home/jdanek/repos/skupper-router/src/dispatch.c:344
#15 0x000000000048fb4e in main_process (config_path=0x7ffe3ee7872e "EA1.conf", python_pkgdir=<optimized out>, test_hooks=<optimized out>, fd=2) at /home/jdanek/repos/skupper-router/router/src/main.c:113
#16 0x00000000004265cc in main (argc=5, argv=0x7ffe3ee77028) at /home/jdanek/repos/skupper-router/router/src/main.c:363
```

```

```

**Comment by jiridanek** [comment]
This is in similar area as https://github.com/skupperproject/skupper-router/issues/492 was. I probably should retry with latest main.

**Comment by jiridanek** [comment]
Does not happen on latest main, and starts happening again if I then revert #493, so it looks like that PR fixed this.

**Comment by ganeshmurthy** [comment]
Yay ! That's good news. Thanks for testing and verifying.
