### ISSUE TITLE
[s390x] system_tests_http2_tls CURL ERROR 56:  curl: (56) OpenSSL SSL_read: Connection reset by peer, errno 104

### ISSUE THREAD

**Issue by jiridanek** [skupperproject/skupper-router#671]
This is the first time I see this

```
60: ======================================================================
60: FAIL: test_q2_block_unblock (system_tests_http2_tls.Http2TlsQ2TwoRouterTest)
60: ----------------------------------------------------------------------
60: Traceback (most recent call last):
60:   File "/home/travis/build/skupperproject/skupper-router/tests/system_tests_http2_tls.py", line 346, in test_q2_block_unblock
60:     _, out, _ = self.run_curl(address, args=self.get_all_curl_args(['-X', 'POST',
60:   File "/home/travis/build/skupperproject/skupper-router/tests/system_tests_http2.py", line 130, in run_curl
60:     assert status == 0, f"CURL ERROR {status}: {out} {err}"
60: AssertionError: CURL ERROR 56:  curl: (56) OpenSSL SSL_read: Connection reset by peer, errno 104
60: 
60: 
60: 
60: ----------------------------------------------------------------------
60: Ran 65 tests in 136.177s
60: 
60: FAILED (failures=1)
59/68 Test #60: system_tests_http2_tls ..................***Failed  143.78 sec
```

https://app.travis-ci.com/github/skupperproject/skupper-router/jobs/578952844#L5691

**Comment by jiridanek** [comment]
Related to https://github.com/skupperproject/skupper-router/issues/417 (the more verbose assert was added as part of that issue).

**Comment by ganeshmurthy** [comment]
We are moving to the new TCPLite  adaptor with protocol adaptors, closing this
