### ISSUE TITLE
`assert output["bytesIn"] == output["bytesOut"]` fails in system_tests_tcp_adaptor_tls

### ISSUE THREAD

**Issue by jiridanek** [skupperproject/skupper-router#959]
https://github.com/skupperproject/skupper-router/actions/runs/4186029481/jobs/7254037161#step:10:3134

```
61:     def test_80_stats(self):
61:         tname = "test_80 check stats in skmanage"
61:         self.logger.log(tname + " START")
61:         # Verify listener stats
61:         query_command = 'QUERY --type=tcpListener'
61:         outputs = json.loads(self.run_skmanage(query_command))
61:         es_inta_connections_opened = 0
61:         for output in outputs:
61:             if output['address'].startswith("ES"):
61:                 if output['address'] == 'ES_INTA':
61:                     es_inta_connections_opened += output["connectionsOpened"]
61:                 # Check only echo server listeners
61:                 assert "connectionsOpened" in output
61:                 # There is a listener with authenticatePeer:yes and we have not run any tests on it yet, so
61:                 # it is allowed to have zero connectionsOpened
61:                 if output['address'] != 'ES_INTA' and output['address'] != 'ES_BAD_CONNECTOR_CERT_INTA' \
61:                         and output['address'] != 'ES_GOOD_CONNECTOR_CERT_INTA' \
61:                         and output['address'] != 'ES_ALL':
61:                     assert output["connectionsOpened"] > 0
61: >               assert output["bytesIn"] == output["bytesOut"]
61: E               assert 501106 == 501101
61: 
61: /home/runner/work/skupper-router/skupper-router/skupper-router/tests/system_tests_tcp_adaptor.py:1336: AssertionError
```

**Comment by jiridanek** [comment]
```
======================================================================
FAIL: test_50_concurrent_interior (system_tests_tcp_adaptor_tls.TcpTlsAdaptor.test_50_concurrent_interior)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/skupper-router/tests/system_tests_tcp_adaptor.py", line 1167, in test_50_concurrent_interior
    assert result is None, "TCP_TEST Stop %s FAIL: %s" % (name, result)
           ^^^^^^^^^^^^^^
AssertionError: TCP_TEST Stop test_50_concurrent_interior FAIL: TCP_TEST TIMEOUT - local wait time exceeded

======================================================================
FAIL: test_80_stats (system_tests_tcp_adaptor_tls.TcpTlsAdaptor.test_80_stats)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/skupper-router/tests/system_tests_tcp_adaptor.py", line 1336, in test_80_stats
    assert output["bytesIn"] == output["bytesOut"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

======================================================================
FAIL: test_90_balancing (system_tests_tcp_adaptor_tls.TcpTlsAdaptor.test_90_balancing)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/skupper-router/tests/system_tests_tcp_adaptor.py", line 1358, in test_90_balancing
    self.assertIsNone(result)
AssertionError: 'TCP_TEST TIMEOUT - local wait time exceeded' is not None

----------------------------------------------------------------------
Ran 37 tests in 204.116s
```

https://download.copr.fedorainfracloud.org/results/packit/skupperproject-skupper-router-1014/fedora-rawhide-s390x/05706353-skupper-router/builder-live.log.gz

**Comment by ganeshmurthy** [comment]
Closing this since we have not seen this for a year
