### ISSUE TITLE
SEGFAULT in _vflow_set_int_TH during Http1AdaptorBadEndpointsTest::test_08_bad_chunked_body test

### ISSUE THREAD

**Issue by kgiusti** [skupperproject/skupper-router#966]
https://github.com/skupperproject/skupper-router/actions/runs/4244471490/jobs/7378637317#step:30:3233

This test simulates badly formatted HTTP/1 messages with chunked body encoding. The router will respond by closing the associated connection when the parse error is hit. The crash occurs shortly after the last connection closes.

The fault appears to occur during _vflow_find_attribute():

```c
  static vflow_attribute_data_t* _vflow_find_attribute(vflow_record_t *record, vflow_attribute_t attr)
  {
    vflow_attribute_data_t *data = DEQ_TAIL(record->attributes);
    while(!!data) {
     if (data->attribute_type <= attr) {  <<<<<< HERE

```

```
2023-02-22T16:03:46.1800912Z Program terminated with signal SIGSEGV, Segmentation fault.
2023-02-22T16:03:46.1801241Z #0  0x00007fd690d7eb8f in raise () from /lib64/libpthread.so.0
2023-02-22T16:03:46.1953650Z [Current thread is 1 (Thread 0x7fd6895c6700 (LWP 5506))]
2023-02-22T16:03:46.1953843Z 
2023-02-22T16:03:46.1953962Z Thread 7 (Thread 0x7fd6865c3700 (LWP 5509)):
2023-02-22T16:03:46.1954258Z #0  0x00007fd690d7db47 in close () from /lib64/libpthread.so.0
2023-02-22T16:03:46.1954992Z #1  0x00007fd6915ebd3b in pclosefd (fd=<optimized out>, p=0x2d3ce30) at /home/runner/work/skupper-router/skupper-router/qpid-proton/c/src/proactor/epoll.c:755
2023-02-22T16:03:46.1955751Z #2  praw_connection_cleanup (prc=<optimized out>, prc=<optimized out>) at /home/runner/work/skupper-router/skupper-router/qpid-proton/c/src/proactor/epoll_raw_connection.c:155
2023-02-22T16:03:46.1956517Z #3  0x00007fd6915efd36 in pni_raw_connection_done (rc=0x3acd1c0) at /home/runner/work/skupper-router/skupper-router/qpid-proton/c/src/proactor/epoll_raw_connection.c:431
2023-02-22T16:03:46.1957284Z #4  pn_proactor_done (p=<optimized out>, batch=<optimized out>, p=<optimized out>, batch=<optimized out>) at /home/runner/work/skupper-router/skupper-router/qpid-proton/c/src/proactor/epoll.c:2734
2023-02-22T16:03:46.1993589Z #5  0x00000000004a6c90 in thread_run (arg=0x2d198b0) at /home/runner/work/skupper-router/skupper-router/skupper-router/src/server.c:1135
2023-02-22T16:03:46.1994005Z #6  0x00007fd690d741ca in start_thread () from /lib64/libpthread.so.0
2023-02-22T16:03:46.2014778Z #7  0x00007fd68fab1e73 in clone () from /lib64/libc.so.6
2023-02-22T16:03:46.2024051Z 
2023-02-22T16:03:46.2024200Z Thread 6 (Thread 0x7fd6875c4700 (LWP 5508)):
2023-02-22T16:03:46.2024534Z #0  0x00007fd690d7a45c in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
2023-02-22T16:03:46.2025180Z #1  0x00007fd6915f117b in suspend (ts=0x2a977b0, p=0x2d3ce30) at /home/runner/work/skupper-router/skupper-router/qpid-proton/c/src/proactor/epoll.c:401
2023-02-22T16:03:46.2025944Z #2  next_event_batch (p=0x2d3ce30, can_block=true) at /home/runner/work/skupper-router/skupper-router/qpid-proton/c/src/proactor/epoll.c:2490
2023-02-22T16:03:46.2026584Z #3  0x00000000004a6ba6 in thread_run (arg=0x2d198b0) at /home/runner/work/skupper-router/skupper-router/skupper-router/src/server.c:1102
2023-02-22T16:03:46.2026985Z #4  0x00007fd690d741ca in start_thread () from /lib64/libpthread.so.0
2023-02-22T16:03:46.2027288Z #5  0x00007fd68fab1e73 in clone () from /lib64/libc.so.6
2023-02-22T16:03:46.2031564Z 
2023-02-22T16:03:46.2031696Z Thread 5 (Thread 0x7fd6885c5700 (LWP 5507)):
2023-02-22T16:03:46.2032021Z #0  0x00007fd690d7a45c in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
2023-02-22T16:03:46.2064410Z #1  0x0000000000471b09 in sys_cond_wait (cond=cond@entry=0x2ddad90, held_mutex=held_mutex@entry=0x2ddadc0) at /home/runner/work/skupper-router/skupper-router/skupper-router/src/posix/threading.c:81
2023-02-22T16:03:46.2082372Z #2  0x000000000048fe0c in router_core_thread (arg=0x2ddad40) at /home/runner/work/skupper-router/skupper-router/skupper-router/src/router_core/router_core_thread.c:227
2023-02-22T16:03:46.2082845Z #3  0x00007fd690d741ca in start_thread () from /lib64/libpthread.so.0
2023-02-22T16:03:46.2083142Z #4  0x00007fd68fab1e73 in clone () from /lib64/libc.so.6
2023-02-22T16:03:46.2083307Z 
2023-02-22T16:03:46.2083423Z Thread 4 (Thread 0x7fd6855c2700 (LWP 5510)):
2023-02-22T16:03:46.2083710Z #0  0x00007fd68fba6e87 in epoll_wait () from /lib64/libc.so.6
2023-02-22T16:03:46.2084360Z #1  0x00007fd6915f1287 in poller_do_epoll (can_block=true, ts=0x2ccbcb0, p=0x2d3ce30) at /home/runner/work/skupper-router/skupper-router/qpid-proton/c/src/proactor/epoll.c:2534
2023-02-22T16:03:46.2085038Z #2  next_event_batch (p=0x2d3ce30, can_block=true) at /home/runner/work/skupper-router/skupper-router/qpid-proton/c/src/proactor/epoll.c:2473
2023-02-22T16:03:46.2085676Z #3  0x00000000004a6ba6 in thread_run (arg=0x2d198b0) at /home/runner/work/skupper-router/skupper-router/skupper-router/src/server.c:1102
2023-02-22T16:03:46.2086076Z #4  0x00007fd690d741ca in start_thread () from /lib64/libpthread.so.0
2023-02-22T16:03:46.2086366Z #5  0x00007fd68fab1e73 in clone () from /lib64/libc.so.6
2023-02-22T16:03:46.2086620Z 
2023-02-22T16:03:46.2086736Z Thread 3 (Thread 0x7fd691a0f300 (LWP 5503)):
2023-02-22T16:03:46.2087053Z #0  0x00007fd690d756cd in __pthread_timedjoin_ex () from /lib64/libpthread.so.0
2023-02-22T16:03:46.2087623Z #1  0x00000000004a5b77 in qd_server_run (qd=<optimized out>) at /home/runner/work/skupper-router/skupper-router/skupper-router/src/server.c:1517
2023-02-22T16:03:46.2088460Z #2  0x0000000000427cc7 in main_process (config_path=0x7ffffad8cee6 "TestBadEndpoints.conf", python_pkgdir=<optimized out>, test_hooks=<optimized out>, fd=2) at /home/runner/work/skupper-router/skupper-router/skupper-router/router/src/main.c:109
2023-02-22T16:03:46.2089229Z #3  0x0000000000427819 in main (argc=5, argv=0x7ffffad8b458) at /home/runner/work/skupper-router/skupper-router/skupper-router/router/src/main.c:363
2023-02-22T16:03:46.2089495Z 
2023-02-22T16:03:46.2089609Z Thread 2 (Thread 0x7fd6845c1700 (LWP 5511)):
2023-02-22T16:03:46.2089924Z #0  0x00007fd690d7a45c in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
2023-02-22T16:03:46.2090520Z #1  0x00007fd6915f117b in suspend (ts=0x29ea070, p=0x2d3ce30) at /home/runner/work/skupper-router/skupper-router/qpid-proton/c/src/proactor/epoll.c:401
2023-02-22T16:03:46.2091157Z #2  next_event_batch (p=0x2d3ce30, can_block=true) at /home/runner/work/skupper-router/skupper-router/qpid-proton/c/src/proactor/epoll.c:2490
2023-02-22T16:03:46.2091786Z #3  0x00000000004a6ba6 in thread_run (arg=0x2d198b0) at /home/runner/work/skupper-router/skupper-router/skupper-router/src/server.c:1102
2023-02-22T16:03:46.2092176Z #4  0x00007fd690d741ca in start_thread () from /lib64/libpthread.so.0
2023-02-22T16:03:46.2092476Z #5  0x00007fd68fab1e73 in clone () from /lib64/libc.so.6
2023-02-22T16:03:46.2092637Z 
2023-02-22T16:03:46.2092751Z Thread 1 (Thread 0x7fd6895c6700 (LWP 5506)):
2023-02-22T16:03:46.2093040Z #0  0x00007fd690d7eb8f in raise () from /lib64/libpthread.so.0
2023-02-22T16:03:46.2110169Z Undefined command: "py-bt".  Try "help".
2023-02-22T16:03:46.2110429Z #1  <signal handler called>
2023-02-22T16:03:46.2110970Z #2  _vflow_find_attribute (record=0x3362750, attr=VFLOW_ATTRIBUTE_OCTETS) at /home/runner/work/skupper-router/skupper-router/skupper-router/src/vanflow.c:197
2023-02-22T16:03:46.2111631Z #3  _vflow_set_int_TH (work=0x2fa0490, discard=<optimized out>) at /home/runner/work/skupper-router/skupper-router/skupper-router/src/vanflow.c:470
2023-02-22T16:03:46.2112271Z #4  0x0000000000476af7 in _vflow_thread (context=0x2ddad40) at /home/runner/work/skupper-router/skupper-router/skupper-router/src/vanflow.c:1216
2023-02-22T16:03:46.2112681Z #5  0x00007fd690d741ca in start_thread () from /lib64/libpthread.so.0
2023-02-22T16:03:46.2112979Z #6  0x00007fd68fab1e73 in clone () from /lib64/libc.so.6
```

**Comment by kgiusti** [comment]
Hit again - centos stream 8, proton 0.38:

https://github.com/kgiusti/skupper-router/actions/runs/4388480916/jobs/7685026995#step:33:53
